import React, { useState } from 'react';
import { Download, FileText, FileSpreadsheet, FileJson } from 'lucide-react';
import { useNotification } from '../../context/NotificationContext';
import { useAnalyticsContext } from '../../context/AnalyticsContext';
import { getAuth } from 'firebase/auth';
import autoTable from 'jspdf-autotable';
import seceHeader from '../../assets/sece header.jpeg';

const toDisplayDate = (value) => {
  if (!value) return '-';
  const date = new Date(value?.toDate ? value.toDate() : value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-GB');
};

const getEventDate = (event) => event?.startDate || event?.eventStartDate || event?.date || event?.createdAt;

const countBy = (items, getKey) => Object.entries(items.reduce((result, item) => {
  const key = getKey(item) || 'Not specified';
  result[key] = (result[key] || 0) + 1;
  return result;
}, {})).map(([label, value]) => ({ label, value }));

const drawBarChart = (doc, { x, y, width, height, title, entries, color }) => {
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x, y, width, height, 3, 3, 'FD');
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(title, x + 5, y + 8);
  const chartEntries = entries.slice(0, 5);
  const max = Math.max(...chartEntries.map((entry) => entry.value), 1);
  chartEntries.forEach((entry, index) => {
    const rowY = y + 16 + (index * 8);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    const label = String(entry.label).length > 18 ? `${String(entry.label).slice(0, 17)}...` : String(entry.label);
    doc.setTextColor(71, 85, 105);
    doc.text(label, x + 5, rowY + 4);
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(x + 47, rowY, width - 63, 4.5, 1, 1, 'F');
    doc.setFillColor(...color);
    doc.roundedRect(x + 47, rowY, ((width - 63) * entry.value) / max, 4.5, 1, 1, 'F');
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text(String(entry.value), x + width - 10, rowY + 4, { align: 'right' });
  });
};

const ExportPanel = ({ reportName, data, headers, currentUser, filters = {} }) => {
  const [isExporting, setIsExporting] = useState(false);
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);
  const { showNotification } = useNotification();
  const { metrics, filteredEvents, odRequests } = useAnalyticsContext();

  const INSTITUTION_NAME = 'Sri Eshwar College of Engineering';

  const formatFilterString = () => {
    const activeFilters = Object.entries(filters).filter(([k, v]) => v).map(([k, v]) => `${k}: ${v}`);
    return activeFilters.length > 0 ? activeFilters.join(' | ') : 'None';
  };

  const getHeaderInfo = () => [
    [INSTITUTION_NAME],
    [`Report Title: ${reportName}`],
    [`Generated By: ${currentUser?.name || currentUser?.email} (${currentUser?.role})`],
    [`Generated Date: ${new Date().toLocaleString()}`],
    [`Applied Filters: ${formatFilterString()}`],
    []
  ];

  const logExport = async (exportType) => {
    try {
      const auth = getAuth();
      const token = await auth.currentUser?.getIdToken();
      if (!token) return;

      await fetch(`${import.meta.env.VITE_API_URL}/api/analytics/log-export`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          exportType,
          reportName,
          status: 'SUCCESS'
        })
      });
    } catch (error) {
      console.error('Failed to log export:', error);
    }
  };

  const handleExportCSV = async () => {
    setIsExporting(true);
    try {
      if (!data || data.length === 0) {
        showNotification('No data to export', 'error');
        return;
      }
      
      const csvRows = [];
      const headerInfo = getHeaderInfo();
      headerInfo.forEach(row => csvRows.push(row.join(',')));

      if (headers) csvRows.push(headers.join(','));
      else if (data.length > 0) csvRows.push(Object.keys(data[0]).join(','));

      for (const row of data) {
        const values = Object.values(row).map(val => {
           const escaped = ('' + val).replace(/"/g, '""');
           return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
      }

      const csvString = csvRows.join('\n');
      const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `${reportName}_${new Date().toISOString().split('T')[0]}.csv`;
      link.click();
      
      await logExport('CSV');
      showNotification('CSV exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export CSV', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportExcel = async () => {
    setIsExporting(true);
    try {
       const XLSX = await import('xlsx');
       const worksheet = XLSX.utils.json_to_sheet(data, { origin: 'A7' });
       
       const headerInfo = getHeaderInfo();
       XLSX.utils.sheet_add_aoa(worksheet, headerInfo, { origin: 'A1' });

       if (headers) {
          XLSX.utils.sheet_add_aoa(worksheet, [headers], { origin: 'A7' });
       }
       const workbook = XLSX.utils.book_new();
       XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
       XLSX.writeFile(workbook, `${reportName}_${new Date().toISOString().split('T')[0]}.xlsx`);
       
       await logExport('Excel');
       showNotification('Excel exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export Excel', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
       const { jsPDF } = await import('jspdf');
       // ISO A4 portrait: exactly 210 x 297 mm (21 x 29.7 cm).
       // The report is reflowed vertically so it remains legible on this page size.
       const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
       const reportDate = new Date();
       const pageWidth = doc.internal.pageSize.getWidth();
       const pageHeight = doc.internal.pageSize.getHeight();
       const margin = 12;
       
       const img = new Image();
       img.src = seceHeader;
       
       await new Promise((resolve, reject) => {
           img.onload = resolve;
           img.onerror = reject;
       });
       
       const reportTitle = reportName.includes('Department') ? 'Departmental Analytics Report' : 'Institutional Analytics Report';
       const drawHeader = () => {
         doc.setFillColor(15, 23, 42);
         doc.rect(0, 0, pageWidth, 27, 'F');
         doc.addImage(img, 'JPEG', margin, 5, 38, 15);
         doc.setTextColor(255, 255, 255);
         doc.setFont('helvetica', 'bold');
         doc.setFontSize(14);
         doc.text(INSTITUTION_NAME, 55, 12);
         doc.setFont('helvetica', 'normal');
         doc.setFontSize(8);
         doc.text(`${reportTitle} - IQAC and Accreditation Documentation`, 55, 18);
         doc.setTextColor(30, 41, 59);
       };

       const drawSectionTitle = (title, subtitle, y) => {
         doc.setFont('helvetica', 'bold');
         doc.setFontSize(11);
         doc.setTextColor(15, 23, 42);
         doc.text(title, margin, y);
         doc.setFont('helvetica', 'normal');
         doc.setFontSize(8);
         doc.setTextColor(100, 116, 139);
         doc.text(subtitle, margin, y + 4.5);
       };

       drawHeader();
       let y = 36;
       doc.setFont('helvetica', 'bold');
       doc.setFontSize(18);
       doc.setTextColor(15, 23, 42);
       doc.text(reportTitle, margin, y);
       y += 7;
       doc.setFont('helvetica', 'normal');
       doc.setFontSize(8.5);
       doc.setTextColor(71, 85, 105);
       doc.text(`Generated: ${reportDate.toLocaleString()}  |  Prepared by: ${currentUser?.name || currentUser?.email || 'Institution User'}  |  Role: ${(currentUser?.role || 'IQAC').replaceAll('_', ' ')}`, margin, y);
       y += 6;
       doc.setFillColor(239, 246, 255);
       doc.roundedRect(margin, y, pageWidth - (margin * 2), 10, 2, 2, 'F');
       doc.setFont('helvetica', 'bold');
       doc.setFontSize(8);
       doc.setTextColor(30, 64, 175);
       doc.text('APPLIED FILTERS', margin + 4, y + 4);
       doc.setFont('helvetica', 'normal');
       doc.setTextColor(51, 65, 85);
       doc.text(formatFilterString(), margin + 4, y + 7.5);
       y += 16;

       const kpiEntries = Object.entries(metrics?.kpis || (data?.[0] || {})).slice(0, 8);
       if (kpiEntries.length) {
         doc.setFont('helvetica', 'bold');
         doc.setFontSize(11);
         doc.setTextColor(15, 23, 42);
         doc.text('Executive KPI Summary', margin, y);
         y += 4;
         kpiEntries.forEach(([label, value], index) => {
           const column = index % 4;
           const row = Math.floor(index / 4);
           const cardWidth = (pageWidth - (margin * 2) - 9) / 4;
           const cardX = margin + (column * (cardWidth + 3));
           const cardY = y + (row * 18);
           doc.setFillColor(248, 250, 252);
           doc.setDrawColor(226, 232, 240);
           doc.roundedRect(cardX, cardY, cardWidth, 15, 2, 2, 'FD');
           doc.setFontSize(7.5);
           doc.setFont('helvetica', 'bold');
           doc.setTextColor(100, 116, 139);
           doc.text(label.replace(/([A-Z])/g, ' $1').trim().toUpperCase(), cardX + 4, cardY + 5);
           doc.setFontSize(14);
           doc.setTextColor(15, 23, 42);
           doc.text(String(value ?? '-'), cardX + 4, cardY + 11.5);
         });
         y += Math.ceil(kpiEntries.length / 4) * 18 + 5;
       }

       const events = Array.isArray(filteredEvents) ? filteredEvents : [];
       const requests = Array.isArray(odRequests) ? odRequests : [];
       const statusData = countBy(events, (event) => event.status || 'Draft');
       const monthData = countBy(events, (event) => {
         const date = new Date(getEventDate(event));
         return Number.isNaN(date.getTime()) ? 'Undated' : date.toLocaleDateString('en-GB', { month: 'short', year: 'numeric' });
       });
       const departmentData = countBy(events, (event) => event.department);
       const attended = requests.filter((request) => request.attendanceStatus && request.attendanceStatus !== 'NOT_ATTENDED').length;
       const feedbackResponses = requests.filter((request) => request.feedback).length;
       const feedbackAverage = Number(metrics?.kpis?.avgFeedback || 0);
       const chartWidth = pageWidth - (margin * 2);
       // Portrait A4 uses full-width charts. This avoids cramped labels and
       // makes the report easy to print at the requested 21 x 29.7 cm size.
       drawSectionTitle('Executive analytics', 'Distribution and trend summaries derived from the selected records.', y + 2);
       y += 10;
       drawBarChart(doc, { x: margin, y, width: chartWidth, height: 62, title: 'Event Status Distribution', entries: statusData, color: [37, 99, 235] });

       doc.addPage();
       drawHeader();
       drawSectionTitle('Institutional performance analysis', 'Departmental reach, attendance and feedback completion.', 38);
       const analysisY = 47;
       drawBarChart(doc, { x: margin, y: analysisY, width: chartWidth, height: 62, title: 'Monthly Event Trend', entries: monthData, color: [124, 58, 237] });
       drawBarChart(doc, { x: margin, y: analysisY + 70, width: chartWidth, height: 62, title: 'Department Distribution', entries: departmentData, color: [5, 150, 105] });
       drawBarChart(doc, { x: margin, y: analysisY + 140, width: chartWidth, height: 62, title: 'Attendance and Feedback', entries: [
         { label: 'Registrations', value: requests.length }, { label: 'Attended', value: attended }, { label: 'Feedback responses', value: feedbackResponses }, { label: 'Average feedback x 20', value: Math.round(feedbackAverage * 20) }
       ], color: [217, 119, 6] });

       doc.addPage();
       drawHeader();
       drawSectionTitle('Detailed event register', 'Event-level evidence for institutional review and accreditation documentation.', 38);
       const tableRows = events.map((event, index) => [
         index + 1,
         event.title || event.eventName || 'Untitled event',
         event.department || '-',
         event.eventType || event.category || '-',
         toDisplayDate(getEventDate(event)),
         event.status || '-',
         event.registrationCount ?? event.participants ?? '-'
       ]);
       autoTable(doc, {
         startY: 44,
         margin: { left: margin, right: margin, top: 35, bottom: 16 },
         head: [['No.', 'Event title', 'Department', 'Category', 'Start date', 'Status', 'Participants']],
         body: tableRows.length ? tableRows : [['-', 'No events match the applied filters', '-', '-', '-', '-', '-']],
         theme: 'grid',
         showHead: 'everyPage',
         headStyles: { fillColor: [30, 58, 95], textColor: 255, fontStyle: 'bold', fontSize: 7.5, cellPadding: 2.2, valign: 'middle', overflow: 'visible' },
         styles: { fontSize: 7.5, cellPadding: 2.2, textColor: [30, 41, 59], valign: 'middle', overflow: 'linebreak' },
         alternateRowStyles: { fillColor: [248, 250, 252] },
         columnStyles: { 0: { cellWidth: 9 }, 1: { cellWidth: 57 }, 2: { cellWidth: 23 }, 3: { cellWidth: 24 }, 4: { cellWidth: 22 }, 5: { cellWidth: 28 }, 6: { cellWidth: 23, halign: 'right' } },
         didDrawPage: () => drawHeader()
       });

       const pageCount = doc.getNumberOfPages();
       for (let page = 1; page <= pageCount; page += 1) {
         doc.setPage(page);
         doc.setDrawColor(203, 213, 225);
         doc.line(margin, pageHeight - 11, pageWidth - margin, pageHeight - 11);
         doc.setFont('helvetica', 'normal');
         doc.setFontSize(7.5);
         doc.setTextColor(100, 116, 139);
         doc.text('Confidential institutional document - suitable for IQAC, NAAC, NBA and accreditation review.', margin, pageHeight - 6);
         doc.text(`Page ${page} of ${pageCount}`, pageWidth - margin, pageHeight - 6, { align: 'right' });
       }

       doc.save(`${reportName}_${reportDate.toISOString().split('T')[0]}.pdf`);
       
       await logExport('PDF');
       showNotification('PDF exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export PDF', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="relative self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div>
        <p className="text-xs font-bold uppercase tracking-wider text-blue-600">Institutional exports</p>
        <h4 className="mt-1 font-extrabold text-slate-800">Accreditation-ready reports</h4>
        <p className="mt-1 text-sm text-slate-500">Generate a formatted institutional report or source dataset.</p>
      </div>
      <div className="relative mt-5">
        <button onClick={() => setIsExportMenuOpen((open) => !open)} disabled={isExporting} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-50"><Download size={16} /> {isExporting ? 'Preparing export...' : 'Export report'}</button>
        {isExportMenuOpen && <div className="absolute bottom-full left-0 right-0 z-20 mb-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><p className="px-2 pb-2 pt-1 text-[11px] font-extrabold uppercase tracking-wider text-slate-400">Choose export format</p><button onClick={() => { setIsExportMenuOpen(false); handleExportPDF(); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition hover:bg-red-50"><span className="rounded-lg bg-red-50 p-2 text-red-600"><FileText size={16} /></span><span><span className="block text-sm font-bold text-slate-800">Institutional PDF Report</span><span className="block text-xs text-slate-500">Formatted IQAC and accreditation report</span></span></button><button onClick={() => { setIsExportMenuOpen(false); handleExportExcel(); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition hover:bg-emerald-50"><span className="rounded-lg bg-emerald-50 p-2 text-emerald-600"><FileSpreadsheet size={16} /></span><span><span className="block text-sm font-bold text-slate-800">Excel Dataset</span><span className="block text-xs text-slate-500">Structured data for analysis</span></span></button><button onClick={() => { setIsExportMenuOpen(false); handleExportCSV(); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition hover:bg-blue-50"><span className="rounded-lg bg-blue-50 p-2 text-blue-600"><FileJson size={16} /></span><span><span className="block text-sm font-bold text-slate-800">CSV Dataset</span><span className="block text-xs text-slate-500">Lightweight spreadsheet export</span></span></button></div>}
      </div>
    </div>
  );
};

export default ExportPanel;
