import React, { useState } from 'react';
import { Download, FileText, FileSpreadsheet, FileJson } from 'lucide-react';
import { useNotification } from '../../context/NotificationContext';
import { getAuth } from 'firebase/auth';
import autoTable from 'jspdf-autotable';
import seceHeader from '../../assets/sece header.jpeg';
const ExportPanel = ({ reportName, data, headers, currentUser, filters = {} }) => {
  const [isExporting, setIsExporting] = useState(false);
  const { showNotification } = useNotification();

  const INSTITUTION_NAME = 'Sri Eshwar College of Engineering';

  const formatFilterString = () => {
    const activeFilters = Object.entries(filters).filter(([k, v]) => v).map(([k, v]) => `${k}: ${v}`);
    return activeFilters.length > 0 ? activeFilters.join(' | ') : 'None';
  };

  const getHeaderInfo = () => [
    [INSTITUTION_NAME],
    [`Report Title: ${reportName}`],
    [`Generated By: ${currentUser?.name || currentUser?.email} (${currentUser?.role})`],
    [`Generated Date: ${new Date().toLocaleString()}`],
    [`Applied Filters: ${formatFilterString()}`],
    []
  ];

  const logExport = async (exportType) => {
    try {
      const auth = getAuth();
      const token = await auth.currentUser?.getIdToken();
      if (!token) return;

      await fetch(`${import.meta.env.VITE_API_URL}/api/analytics/log-export`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          exportType,
          reportName,
          status: 'SUCCESS'
        })
      });
    } catch (error) {
      console.error('Failed to log export:', error);
    }
  };

  const handleExportCSV = async () => {
    setIsExporting(true);
    try {
      if (!data || data.length === 0) {
        showNotification('No data to export', 'error');
        return;
      }
      
      const csvRows = [];
      const headerInfo = getHeaderInfo();
      headerInfo.forEach(row => csvRows.push(row.join(',')));

      if (headers) csvRows.push(headers.join(','));
      else if (data.length > 0) csvRows.push(Object.keys(data[0]).join(','));

      for (const row of data) {
        const values = Object.values(row).map(val => {
           const escaped = ('' + val).replace(/"/g, '""');
           return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
      }

      const csvString = csvRows.join('\n');
      const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `${reportName}_${new Date().toISOString().split('T')[0]}.csv`;
      link.click();
      
      await logExport('CSV');
      showNotification('CSV exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export CSV', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportExcel = async () => {
    setIsExporting(true);
    try {
       const XLSX = await import('xlsx');
       const worksheet = XLSX.utils.json_to_sheet(data, { origin: 'A7' });
       
       const headerInfo = getHeaderInfo();
       XLSX.utils.sheet_add_aoa(worksheet, headerInfo, { origin: 'A1' });

       if (headers) {
          XLSX.utils.sheet_add_aoa(worksheet, [headers], { origin: 'A7' });
       }
       const workbook = XLSX.utils.book_new();
       XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
       XLSX.writeFile(workbook, `${reportName}_${new Date().toISOString().split('T')[0]}.xlsx`);
       
       await logExport('Excel');
       showNotification('Excel exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export Excel', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
       const { jsPDF } = await import('jspdf');
       const doc = new jsPDF();
       
       const img = new Image();
       img.src = seceHeader;
       
       await new Promise((resolve, reject) => {
           img.onload = resolve;
           img.onerror = reject;
       });
       
       const imgWidth = 190;
       const imgHeight = (img.height * imgWidth) / img.width;
       doc.addImage(img, 'JPEG', 10, 10, imgWidth, imgHeight);
       
       let y = 10 + imgHeight + 10;
       
       doc.setFontSize(16);
       doc.setFont("helvetica", "bold");
       doc.text(reportName, 14, y);
       y += 8;
       
       doc.setFontSize(10);
       doc.setFont("helvetica", "normal");
       doc.text(`Generated By: ${currentUser?.name || currentUser?.email} (${currentUser?.role})`, 14, y);
       y += 6;
       doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, y);
       y += 6;
       doc.text(`Applied Filters: ${formatFilterString()}`, 14, y);
       y += 10;
       
       if (data.length > 0) {
           const tableHeaders = headers ? [headers] : [Object.keys(data[0])];
           const tableData = data.map(row => Object.values(row));
           
           autoTable(doc, {
               startY: y,
               head: tableHeaders,
               body: tableData,
               theme: 'grid',
               headStyles: { fillColor: [41, 128, 185], textColor: 255 },
               styles: { fontSize: 8, cellPadding: 3 },
               alternateRowStyles: { fillColor: [245, 245, 245] }
           });
       }

       doc.save(`${reportName}_${new Date().toISOString().split('T')[0]}.pdf`);
       
       await logExport('PDF');
       showNotification('PDF exported successfully', 'success');
    } catch (e) {
      console.error(e);
      showNotification('Failed to export PDF', 'error');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex items-center justify-between">
      <div>
        <h4 className="font-semibold text-slate-800">Export Report</h4>
        <p className="text-sm text-slate-500">Download the analytics dataset</p>
      </div>
      <div className="flex space-x-2">
        <button
          onClick={handleExportPDF}
          disabled={isExporting}
          className="flex items-center px-3 py-2 bg-red-50 text-red-600 rounded-lg hover:bg-red-100 transition-colors text-sm font-medium disabled:opacity-50"
        >
          <FileText size={16} className="mr-2" /> PDF
        </button>
        <button
          onClick={handleExportExcel}
          disabled={isExporting}
          className="flex items-center px-3 py-2 bg-green-50 text-green-600 rounded-lg hover:bg-green-100 transition-colors text-sm font-medium disabled:opacity-50"
        >
          <FileSpreadsheet size={16} className="mr-2" /> Excel
        </button>
        <button
          onClick={handleExportCSV}
          disabled={isExporting}
          className="flex items-center px-3 py-2 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 transition-colors text-sm font-medium disabled:opacity-50"
        >
          <FileJson size={16} className="mr-2" /> CSV
        </button>
      </div>
    </div>
  );
};

export default ExportPanel;
