const EVENT_TYPES = {
  // Event Lifecycle
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_APPROVED: 'EVENT_APPROVED',
  EVENT_REJECTED: 'EVENT_REJECTED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_POSTPONED: 'EVENT_POSTPONED',

  // Registration Lifecycle
  REGISTRATION_SUBMITTED: 'REGISTRATION_SUBMITTED',
  REGISTRATION_APPROVED: 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',
  REGISTRATION_CANCELLED: 'REGISTRATION_CANCELLED',

  // OD Lifecycle
  OD_REQUESTED: 'OD_REQUESTED',
  OD_FACULTY_APPROVED: 'OD_FACULTY_APPROVED',
  OD_HOD_APPROVED: 'OD_HOD_APPROVED',
  OD_REJECTED: 'OD_REJECTED',

  // Post Event Lifecycle
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  IQAC_REVIEW_STARTED: 'IQAC_REVIEW_STARTED',
  REPORT_APPROVED: 'REPORT_APPROVED',
  REPORT_REJECTED: 'REPORT_REJECTED',

  // System
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

module.exports = EVENT_TYPES;
