const EVENT_TYPES = {
  // Event Lifecycle
  DRAFT: 'DRAFT',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_APPROVED: 'EVENT_APPROVED',
  EVENT_REJECTED: 'EVENT_REJECTED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_POSTPONED: 'EVENT_POSTPONED',

  // Registration Lifecycle
  REGISTRATION_SUBMITTED: 'REGISTRATION_SUBMITTED',
  REGISTRATION_APPROVED: 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',
  REGISTRATION_CANCELLED: 'REGISTRATION_CANCELLED',

  // OD Lifecycle
  OD_REQUESTED: 'OD_REQUESTED',
  OD_FACULTY_APPROVED: 'OD_FACULTY_APPROVED',
  OD_HOD_APPROVED: 'OD_HOD_APPROVED',
  OD_REJECTED: 'OD_REJECTED',

  // Post Event Lifecycle
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  IQAC_REVIEW_STARTED: 'IQAC_REVIEW_STARTED',
  REPORT_APPROVED: 'REPORT_APPROVED',
  REPORT_REJECTED: 'REPORT_REJECTED',

  // System
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

const UserRole = {
  STUDENT_GENERAL: 'STUDENT_GENERAL',
  STUDENT_ORGANIZER: 'STUDENT_ORGANIZER',
  FACULTY: 'FACULTY',
  HOD: 'HOD',
  IQAC_TEAM: 'IQAC_TEAM',
  IQAC: 'IQAC_TEAM',
  HR_TEAM: 'HR_TEAM',
  SUPER_ADMIN: 'SUPER_ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  MEDIA: 'MEDIA', // Media Team
  MEDIA_TEAM: 'MEDIA'
};

const EventStatus = {
  DRAFT: 'DRAFT',
  PENDING_FACULTY: 'PENDING_FACULTY',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_DEPARTMENTS: 'PENDING_DEPARTMENTS',
  PENDING_IQAC: 'PENDING_IQAC',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  RUNNING: 'RUNNING',
  ENDED: 'ENDED',
  POST_EVENT_IN_PROGRESS: 'POST_EVENT_IN_PROGRESS',
  PENDING_FACULTY_VERIFICATION: 'PENDING_FACULTY_VERIFICATION',
  PENDING_HOD_VERIFICATION: 'PENDING_HOD_VERIFICATION',
  PENDING_IQAC_VERIFICATION: 'PENDING_IQAC_VERIFICATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED'
};

module.exports = {
  EVENT_TYPES,
  UserRole,
  EventStatus
};
