// Master Constants and Enums for the Application

const Roles = {
  STUDENT_GENERAL: 'STUDENT_GENERAL',
  STUDENT_ORGANIZER: 'STUDENT_ORGANIZER',
  FACULTY: 'FACULTY',
  HOD: 'HOD',
  IQAC_TEAM: 'IQAC_TEAM',
  PRINCIPAL: 'PRINCIPAL',
  HR_TEAM: 'HR_TEAM',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  AUDIO_TEAM: 'AUDIO_TEAM',
  TRANSPORT_TEAM: 'TRANSPORT_TEAM',
  BOYS_WARDEN: 'BOYS_WARDEN',
  GIRLS_WARDEN: 'GIRLS_WARDEN',
  MEDIA: 'MEDIA'
};

const Status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
  SUSPENDED: 'SUSPENDED',
  GRADUATED: 'GRADUATED'
};

const EventApprovalStage = {
  PENDING_CLASS_ADVISOR: 'PENDING_CLASS_ADVISOR',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_DEPARTMENTS: 'PENDING_DEPARTMENTS',
  PENDING_IQAC: 'PENDING_IQAC',
  PENDING_PRINCIPAL: 'PENDING_PRINCIPAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  POSTPONED: 'POSTPONED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

const ODApprovalStage = {
  PENDING_ORGANIZER: 'PENDING_ORGANIZER',
  PENDING_CLASS_ADVISOR: 'PENDING_CLASS_ADVISOR',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_IQAC: 'PENDING_IQAC',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN'
};

const AssignmentType = {
  CLASS_ADVISOR: 'CLASS_ADVISOR',
  MENTOR: 'MENTOR',
  EVENT_COORDINATOR: 'EVENT_COORDINATOR',
  DEPARTMENT_COORDINATOR: 'DEPARTMENT_COORDINATOR',
  PLACEMENT_COORDINATOR: 'PLACEMENT_COORDINATOR',
  NSS_COORDINATOR: 'NSS_COORDINATOR',
  SPORTS_COORDINATOR: 'SPORTS_COORDINATOR'
};

const DocumentType = {
  BROCHURE: 'BROCHURE',
  REPORT: 'REPORT',
  CERTIFICATE: 'CERTIFICATE',
  ATTENDANCE: 'ATTENDANCE',
  POSTER: 'POSTER'
};

const ApprovalAction = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  POSTPONE: 'POSTPONE',
  CANCEL: 'CANCEL'
};

module.exports = {
  Roles,
  Status,
  EventApprovalStage,
  ODApprovalStage,
  AssignmentType,
  DocumentType,
  ApprovalAction
};
