/**
 * Notification Types
 */
const NOTIFICATION_TYPES = {
  EVENT_CREATED: 'EVENT_CREATED',
  VENUE_RESERVED: 'VENUE_RESERVED',
  MANAGER_INVITED: 'MANAGER_INVITED',
  MANAGER_ACCEPTED: 'MANAGER_ACCEPTED',
  EVENT_SUBMITTED: 'EVENT_SUBMITTED',
  APPROVAL_GRANTED: 'APPROVAL_GRANTED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_STARTED: 'EVENT_STARTED',
  EVENT_ENDED: 'EVENT_ENDED',
  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  POST_EVENT_SUBMITTED: 'POST_EVENT_SUBMITTED',
  EVENT_COMPLETED: 'EVENT_COMPLETED',
  EVENT_APPROVED: 'EVENT_APPROVED',
  EVENT_REJECTED: 'EVENT_REJECTED',
  REGISTRATION_APPROVED: 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',
  OD_GENERATED: 'OD_GENERATED',
  OD_APPROVED: 'OD_APPROVED',
  OD_REJECTED: 'OD_REJECTED',
  POST_EVENT_PENDING: 'POST_EVENT_PENDING',
  IQAC_VERIFIED: 'IQAC_VERIFIED',
  REPORT_APPROVED: 'REPORT_APPROVED',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

/**
 * Notification Categories
 */
const NOTIFICATION_CATEGORIES = {
  EVENT: 'EVENT',
  REGISTRATION: 'REGISTRATION',
  OD: 'OD',
  APPROVAL: 'APPROVAL',
  REPORT: 'REPORT',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM: 'SYSTEM'
};

/**
 * Notification Priority Levels
 */
const PRIORITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

/**
 * Notification Lifecycle Statuses
 */
const NOTIFICATION_STATUS = {
  CREATED: 'CREATED',
  DELIVERED: 'DELIVERED',
  VIEWED: 'VIEWED',
  ARCHIVED: 'ARCHIVED',
  FAILED: 'FAILED'
};

/**
 * Channel Enums
 */
const CHANNELS = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL'
};

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_CATEGORIES,
  PRIORITY_LEVELS,
  NOTIFICATION_STATUS,
  CHANNELS
};
