import { fetchEvents } from '../services/firebaseService';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Calendar, MapPin, Loader2, CheckCircle, XCircle, Download, UserPlus, UserMinus, FileCheck, Clock, Users, MessageSquare, X, Star, ClipboardList } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppContext } from '../context/AppContext';
import { EventStatus, UserRole } from '../types';
import Navbar from '../components/Navbar';
import StatusBadge from '../components/StatusBadge';
import ODLetterModal from '../components/ODLetterModal';
import FeedbackModal from '../components/FeedbackModal';
import defaultPoster from '../assets/sece.avif';

// ── IQAC Summary Modal ─────────────────────────────────────────────────────────
const IQACSummaryModal = ({ event, onClose }) => {
  if (!event) return null;
  const s1 = event.requisition?.step1;
  // Backend saves all IQAC data under event.iqacData (not iqacSubmission)
  const iqac = event.iqacData || {};
  const reg     = iqac.registration || {};           // { categories, total, attendance, period, mode }
  const cats    = reg.categories    || {};           // { students, faculty, external } — registered
  const att     = reg.attendance    || {};           // { categories, total, studentAttendanceList }
  const attCats = att.categories    || {};           // { students, faculty, external } — attended

  // Checklist: submitted as iqac.checklist array, fallback: build from iqac.documents object
  // NOTE: backend stores documents as { [labelKey]: { fileName, fileType, fileSize, dataUrl, ... } }
  // so we normalise both paths into { id, requirement, status, file } shape
  const checklist = Array.isArray(iqac.checklist) && iqac.checklist.length > 0
    ? iqac.checklist
    : Object.entries(iqac.documents || {}).map(([req, val]) => ({
        id: req,
        requirement: req,
        status: val?.status || 'pending',
        autoGenerated: Boolean(val?.autoGenerated),
        file: val?.dataUrl ? { dataUrl: val.dataUrl, fileName: val.fileName || `${req}.pdf` } : null,
      }));

  // Gallery: backend saves as { url, title, caption, ... } (not dataUrl)
  const gallery       = Array.isArray(iqac.gallery)       ? iqac.gallery       : [];
  // Guest feedback: backend saves as iqac.guestFeedback (not guestFeedbackList)
  const guestFeedback = Array.isArray(iqac.guestFeedback) ? iqac.guestFeedback : [];
  // Student feedback: from auto-stats feedbackSummary.comments
  const autoFeedback  = iqac.feedbackSummary || null;
  const studentFeedback = autoFeedback?.comments || [];
  // Resource persons: backend saves as iqac.resourcePersons array
  const resourcePersons = Array.isArray(iqac.resourcePersons) ? iqac.resourcePersons : [];
  // Attendance roster: stored under registration.attendance.studentAttendanceList
  const studentRoster = Array.isArray(att.studentAttendanceList) ? att.studentAttendanceList : [];

  const studentsCount    = Number(cats.students)    || 0;
  const facultyCount     = Number(cats.faculty)     || 0;
  const externalCount    = Number(cats.external)    || 0;
  const studentsAttended = Number(attCats.students) || 0;
  const facultyAttended  = Number(attCats.faculty)  || 0;
  const externalAttended = Number(attCats.external) || 0;
  const totalRegistered  = Number(reg.total)        || (studentsCount + facultyCount + externalCount);
  const totalAttended    = Number(att.total)        || (studentsAttended + facultyAttended + externalAttended);
  const attendancePct    = totalRegistered > 0 ? Math.round((totalAttended / totalRegistered) * 100) : 0;

  const submittedOn = event.iqacSubmittedAt
    ? new Date(event.iqacSubmittedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : null;

  const checklistStatusColor = (status) => ({
    verified:      'bg-emerald-100 text-emerald-700',
    autoGenerated: 'bg-slate-100   text-slate-500',
    uploaded:      'bg-blue-100    text-blue-700',
    pending:       'bg-red-50      text-red-500',
  }[status] || 'bg-slate-100 text-slate-500');

  const checklistStatusLabel = (status) => ({
    verified:      'Verified',
    autoGenerated: 'Auto-Generated',
    uploaded:      'Uploaded',
    pending:       'Pending',
  }[status] || status);

  // ── Download helpers ──────────────────────────────────────────────────────────
  const triggerDownload = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const tdStyle = 'border:1px solid #555;padding:7px 10px;font-size:13px;';
  const thStyle = 'border:1px solid #555;padding:8px 10px;font-size:13px;background:#d0e4f7;font-weight:bold;text-align:left;';
  const tableStyle = 'border-collapse:collapse;width:100%;margin-top:10px;';

  const excelWrapper = (title, tableHtml) => `<html xmlns:o='urn:schemas-microsoft-com:office:office'
    xmlns:x='urn:schemas-microsoft-com:office:excel'
    xmlns='http://www.w3.org/TR/REC-html40'>
  <head><meta charset='UTF-8'>
    <style>body{font-family:Arial,sans-serif;padding:20px;}h2{margin-bottom:4px;}p{margin:2px 0;color:#555;}</style>
  </head><body>
    <h2>${title}</h2>
    <p>Event: ${event.title || s1?.eventName || '-'} &nbsp;|&nbsp; Date: ${s1?.eventStartDate || '-'} – ${s1?.eventEndDate || '-'} &nbsp;|&nbsp; Venue: ${event.venue || '-'}</p>
    <p>Generated on: ${new Date().toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' })}</p>
    ${tableHtml}
  </body></html>`;

  const downloadAttendanceExcel = () => {
    const rows = studentRoster.length > 0
      ? studentRoster.map((r, i) => `<tr>
          <td style='${tdStyle}'>${i + 1}</td>
          <td style='${tdStyle}'>${r.student || r.studentName || '—'}</td>
          <td style='${tdStyle}'>${r.rollNo || '—'}</td>
          <td style='${tdStyle}color:${r.attendanceStatus === 'NOT_ATTENDED' ? '#c00' : '#007a00'};font-weight:bold'>
            ${r.attendanceStatus === 'NOT_ATTENDED' ? 'Absent' : 'Present'}</td>
        </tr>`).join('')
      : `<tr><td colspan='4' style='${tdStyle}text-align:center;color:#888'>No attendance data recorded</td></tr>`;

    const table = `<table style='${tableStyle}'>
      <thead><tr>
        <th style='${thStyle}'>#</th>
        <th style='${thStyle}'>Student Name</th>
        <th style='${thStyle}'>Roll No</th>
        <th style='${thStyle}'>Attendance</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
    triggerDownload(
      new Blob([excelWrapper('Attendance Sheet', table)], { type: 'application/vnd.ms-excel;charset=utf-8' }),
      `Attendance_${(event.title || 'Event').replace(/\s+/g,'_')}.xls`
    );
  };

  const downloadParticipantFeedbackExcel = () => {
    const comments = autoFeedback?.comments || studentFeedback || [];
    const rows = comments.length > 0
      ? comments.map((c, i) => `<tr>
          <td style='${tdStyle}'>${i + 1}</td>
          <td style='${tdStyle}'>${c.student || c.name || '—'}</td>
          <td style='${tdStyle}'>${c.rollNo || '—'}</td>
          <td style='${tdStyle}text-align:center'>${'★'.repeat(Number(c.rating) || 0)}${'☆'.repeat(5 - (Number(c.rating) || 0))} (${c.rating || '—'}/5)</td>
          <td style='${tdStyle}'>${c.comment || c.feedback || 'No comment'}</td>
        </tr>`).join('')
      : `<tr><td colspan='5' style='${tdStyle}text-align:center;color:#888'>No participant feedback submitted</td></tr>`;

    const table = `<table style='${tableStyle}'>
      <thead><tr>
        <th style='${thStyle}'>#</th>
        <th style='${thStyle}'>Student Name</th>
        <th style='${thStyle}'>Roll No</th>
        <th style='${thStyle}'>Rating</th>
        <th style='${thStyle}'>Feedback</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
    triggerDownload(
      new Blob([excelWrapper('Feedback from Participants', table)], { type: 'application/vnd.ms-excel;charset=utf-8' }),
      `Participant_Feedback_${(event.title || 'Event').replace(/\s+/g,'_')}.xls`
    );
  };

  const downloadResourcePersonFeedbackExcel = () => {
    const rows = guestFeedback.length > 0
      ? guestFeedback.map((fb, i) => `<tr>
          <td style='${tdStyle}'>${i + 1}</td>
          <td style='${tdStyle}'>${fb.name || '—'}</td>
          <td style='${tdStyle}'>${fb.designation || '—'}</td>
          <td style='${tdStyle}'>${fb.organization || '—'}</td>
          <td style='${tdStyle}text-align:center'>${'★'.repeat(Number(fb.rating) || 0)}${'☆'.repeat(5 - (Number(fb.rating) || 0))} (${fb.rating || '—'}/5)</td>
          <td style='${tdStyle}'>${fb.feedback || 'No comment'}</td>
        </tr>`).join('')
      : `<tr><td colspan='6' style='${tdStyle}text-align:center;color:#888'>No resource person feedback recorded</td></tr>`;

    const table = `<table style='${tableStyle}'>
      <thead><tr>
        <th style='${thStyle}'>#</th>
        <th style='${thStyle}'>Name</th>
        <th style='${thStyle}'>Designation</th>
        <th style='${thStyle}'>Organization</th>
        <th style='${thStyle}'>Rating</th>
        <th style='${thStyle}'>Feedback</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
    triggerDownload(
      new Blob([excelWrapper('Feedback from Resource Person', table)], { type: 'application/vnd.ms-excel;charset=utf-8' }),
      `ResourcePerson_Feedback_${(event.title || 'Event').replace(/\s+/g,'_')}.xls`
    );
  };

  const downloadEventReportHTML = () => {
    const rpRows = resourcePersons.length > 0
      ? resourcePersons.map((rp, i) => `<tr>
          <td>${i + 1}</td><td>${rp.name || '—'}</td><td>${rp.designation || '—'}</td>
          <td>${rp.organization || '—'}</td><td>${rp.topic || '—'}</td>
          <td>${'★'.repeat(Number(rp.rating)||0)}${'☆'.repeat(5-(Number(rp.rating)||0))}</td>
        </tr>`).join('')
      : '<tr><td colspan="6" style="text-align:center;color:#888">No resource persons recorded</td></tr>';

    const attRows = studentRoster.length > 0
      ? studentRoster.map((r, i) => `<tr>
          <td>${i+1}</td><td>${r.student||'—'}</td><td>${r.rollNo||'—'}</td>
          <td style="color:${r.attendanceStatus==='NOT_ATTENDED'?'#c00':'#007a00'};font-weight:bold">
          ${r.attendanceStatus==='NOT_ATTENDED'?'Absent':'Present'}</td>
        </tr>`).join('')
      : '<tr><td colspan="4" style="text-align:center;color:#888">No roster recorded</td></tr>';

    const fbRows = (autoFeedback?.comments || studentFeedback).length > 0
      ? (autoFeedback?.comments || studentFeedback).map((c,i) => `<tr>
          <td>${i+1}</td><td>${c.student||c.name||'—'}</td><td>${c.rollNo||'—'}</td>
          <td>${'★'.repeat(Number(c.rating)||0)}${'☆'.repeat(5-(Number(c.rating)||0))} ${c.rating||'—'}/5</td>
          <td>${c.comment||c.feedback||'—'}</td>
        </tr>`).join('')
      : '<tr><td colspan="5" style="text-align:center;color:#888">No feedback submitted</td></tr>';

    const gfRows = guestFeedback.length > 0
      ? guestFeedback.map((fb,i) => `<tr>
          <td>${i+1}</td><td>${fb.name||'—'}</td><td>${fb.designation||'—'}</td>
          <td>${fb.organization||'—'}</td>
          <td>${'★'.repeat(Number(fb.rating)||0)}${'☆'.repeat(5-(Number(fb.rating)||0))} ${fb.rating||'—'}/5</td>
          <td>${fb.feedback||'—'}</td>
        </tr>`).join('')
      : '<tr><td colspan="6" style="text-align:center;color:#888">No guest feedback recorded</td></tr>';

    const clRows = checklist.map(c => `<tr>
      <td>${c.requirement}</td>
      <td style="color:${c.status==='pending'?'#c00':c.status==='verified'?'#007a00':'#0055cc'};font-weight:bold">${checklistStatusLabel(c.status)}</td>
    </tr>`).join('');

    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>Event Report – ${event.title || 'Event'}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Segoe UI',Arial,sans-serif;background:#f4f6fa;color:#1a1a2e;padding:0}
  .page{max-width:900px;margin:30px auto;background:#fff;border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,.10);overflow:hidden}
  .header{background:linear-gradient(135deg,#1a3a5c,#2563eb);color:#fff;padding:36px 40px 28px}
  .header h1{font-size:26px;font-weight:700;margin-bottom:6px}
  .header p{font-size:13px;opacity:.85}
  .badge{display:inline-block;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.35);border-radius:20px;padding:3px 12px;font-size:11px;font-weight:600;margin-top:10px}
  .body{padding:32px 40px;}
  .section{margin-bottom:32px}
  .section-title{font-size:14px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#2563eb;border-bottom:2px solid #e0e7ff;padding-bottom:6px;margin-bottom:14px}
  .info-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:4px}
  .info-card{background:#f0f4ff;border-radius:8px;padding:10px 14px;}
  .info-card .lbl{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#6b7280;margin-bottom:2px}
  .info-card .val{font-size:14px;font-weight:600;color:#111827}
  .stat-row{display:flex;gap:12px;margin-bottom:14px}
  .stat-box{flex:1;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:12px 10px;text-align:center}
  .stat-box .num{font-size:28px;font-weight:800;color:#15803d}
  .stat-box .lbl{font-size:11px;color:#4ade80;font-weight:600;margin-top:2px}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{background:#1a3a5c;color:#fff;text-align:left;padding:9px 11px;font-size:12px;letter-spacing:.04em}
  td{padding:8px 11px;border-bottom:1px solid #e5e7eb;vertical-align:top}
  tr:nth-child(even) td{background:#f9fafb}
  tr:hover td{background:#eff6ff}
  .footer{background:#f1f5f9;padding:18px 40px;text-align:center;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0}
</style></head>
<body><div class="page">
  <div class="header">
    <h1>${event.title || s1?.eventName || 'Event Report'}</h1>
    <p>📅 ${s1?.eventStartDate||'-'} – ${s1?.eventEndDate||'-'} &nbsp;|&nbsp; 🕐 ${s1?.eventStartTime||'-'} – ${s1?.eventEndTime||'-'} &nbsp;|&nbsp; 📍 ${event.venue||'—'}</p>
    <span class="badge">✓ IQAC Submitted ${submittedOn ? `on ${submittedOn}` : ''}</span>
  </div>
  <div class="body">
    <div class="section">
      <div class="section-title">Event Information</div>
      <div class="info-grid">
        <div class="info-card"><div class="lbl">Organizer</div><div class="val">${event.organizerName||s1?.organizerDetails?.organizerName||'—'}</div></div>
        <div class="info-card"><div class="lbl">Event Type</div><div class="val">${s1?.eventType||'—'}</div></div>
        <div class="info-card"><div class="lbl">Department</div><div class="val">${s1?.organizerDetails?.department||event.department||'—'}</div></div>
        <div class="info-card"><div class="lbl">Prof. Societies</div><div class="val">${Array.isArray(s1?.professionalSocieties)&&s1.professionalSocieties.length?s1.professionalSocieties.join(', '):'—'}</div></div>
        <div class="info-card"><div class="lbl">IIC Activity</div><div class="val">${s1?.isIIC||'No'}</div></div>
        <div class="info-card"><div class="lbl">Mode</div><div class="val">${reg.mode||'—'}</div></div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Attendance Summary</div>
      <div class="stat-row">
        <div class="stat-box"><div class="num">${totalRegistered}</div><div class="lbl">Registered</div></div>
        <div class="stat-box"><div class="num">${totalAttended}</div><div class="lbl">Attended</div></div>
        <div class="stat-box"><div class="num">${Math.max(totalRegistered-totalAttended,0)}</div><div class="lbl">No-Show</div></div>
        <div class="stat-box"><div class="num">${attendancePct}%</div><div class="lbl">Rate</div></div>
      </div>
      <table><thead><tr><th>#</th><th>Student Name</th><th>Roll No</th><th>Attendance</th></tr></thead><tbody>${attRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-title">Resource Persons</div>
      <table><thead><tr><th>#</th><th>Name</th><th>Designation</th><th>Organization</th><th>Topic</th><th>Rating</th></tr></thead><tbody>${rpRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-title">Participant Feedback${autoFeedback?` — Avg Rating: ${autoFeedback.averageRating||'—'}/5 (${autoFeedback.totalResponses||0} responses)`:''}</div>
      <table><thead><tr><th>#</th><th>Student</th><th>Roll No</th><th>Rating</th><th>Comment</th></tr></thead><tbody>${fbRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-title">Guest / Resource Person Feedback</div>
      <table><thead><tr><th>#</th><th>Name</th><th>Designation</th><th>Organization</th><th>Rating</th><th>Feedback</th></tr></thead><tbody>${gfRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-title">Documentation Checklist</div>
      <table><thead><tr><th>Requirement</th><th>Status</th></tr></thead><tbody>${clRows}</tbody></table>
    </div>
  </div>
  <div class="footer">IQAC Event Report &nbsp;|&nbsp; ${event.title || 'Event'} &nbsp;|&nbsp; Generated ${new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</div>
</div></body></html>`;

    triggerDownload(
      new Blob([html], { type: 'text/html;charset=utf-8' }),
      `Event_Report_${(event.title || 'Event').replace(/\s+/g,'_')}.html`
    );
  };

  // Map checklist items to their download action.
  // Items built from iqac.documents use the requirement LABEL as id,
  // so match by label substring (case-insensitive) for the 4 auto-generated types.
  const getDownloadAction = (item) => {
    const req = String(item.requirement || item.id || '').toLowerCase();
    // Auto-generated — generate on the fly
    if (req.includes('attendance sheet') || req.includes('attendance-sheet'))
      return downloadAttendanceExcel;
    if (req.includes('feedback from participants') || req.includes('feedback-participants'))
      return downloadParticipantFeedbackExcel;
    if (req.includes('feedback from resource') || req.includes('feedback-resource-person'))
      return downloadResourcePersonFeedbackExcel;
    if (req.includes('event report') || req.includes('event-report'))
      return downloadEventReportHTML;
    // Uploaded files — serve from dataUrl
    // Check both item.file.dataUrl (checklist array path) and
    // item.dataUrl (documents object path where val fields are promoted)
    const dataUrl = item.file?.dataUrl || item.dataUrl;
    const fileName = item.file?.fileName || item.fileName || `${(item.requirement || 'document').replace(/\s+/g,'_')}.pdf`;
    if (dataUrl) {
      return () => {
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      };
    }
    return null;
  };

  const SectionCard = ({ title, icon, children, accent = 'slate', className = '' }) => (
    <section className={`rounded-2xl border border-${accent}-100 bg-white shadow-sm flex flex-col overflow-hidden ${className}`}>
      <div className={`px-6 py-4 border-b border-${accent}-100 flex items-center gap-2 bg-${accent}-50/30`}>
        <span className={`text-${accent}-600 p-1.5 bg-white rounded-lg shadow-sm ring-1 ring-${accent}-100`}>{icon}</span>
        <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide">{title}</h3>
      </div>
      <div className="px-6 py-5 flex-1 flex flex-col">{children}</div>
    </section>
  );

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md z-50 flex items-center justify-center p-4 sm:p-6" onClick={onClose}>
      <motion.div
        initial={{ scale: 0.95, opacity: 0, y: 15 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.95, opacity: 0, y: 15 }}
        transition={{ type: 'spring', stiffness: 300, damping: 28 }}
        className="bg-slate-50/95 backdrop-blur-3xl border border-white/40 ring-1 ring-slate-900/5 rounded-[2rem] shadow-2xl w-full max-w-6xl max-h-[94vh] flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* ── Premium Header ── */}
        <div className="shrink-0 bg-slate-200/70 border-b border-slate-300 px-6 sm:px-8 py-6 relative overflow-hidden">
          <div className="flex items-start justify-between gap-4 relative z-10">
            <div className="flex-1 min-w-0">
              <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-white border border-slate-300 text-slate-600 text-[10px] font-bold uppercase tracking-widest rounded-full mb-3 shadow-sm transition-colors hover:bg-slate-50">
                <ClipboardList size={12} className="shrink-0 text-slate-500" />
                Post-Event IQAC Report
              </div>
              <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight truncate pr-4">
                {event.title || s1?.eventName || 'Event Report'}
              </h2>
              <p className="text-sm text-slate-600 mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 font-medium">
                <span className="flex items-center gap-1.5"><Calendar size={14} className="text-slate-500" /> {s1?.eventStartDate}{s1?.eventEndDate && s1.eventEndDate !== s1.eventStartDate ? ` – ${s1.eventEndDate}` : ''}</span>
                <span className="flex items-center gap-1.5"><Clock size={14} className="text-slate-500" /> {s1?.eventStartTime} – {s1?.eventEndTime}</span>
                {event.venue && <span className="flex items-center gap-1.5"><MapPin size={14} className="text-slate-500" /> {event.venue}</span>}
              </p>
            </div>
            
            <div className="flex flex-col items-end gap-3 shrink-0">
              <button onClick={onClose} className="p-2 bg-white hover:bg-slate-100 border border-slate-300 text-slate-600 rounded-full transition-colors shadow-sm" title="Close">
                <X size={18} />
              </button>
              {submittedOn && (
                <div className="inline-flex items-center gap-1.5 bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-semibold px-3 py-1.5 rounded-full mt-1 shadow-sm">
                  <FileCheck size={12} className="text-emerald-500" /> Submitted on {submittedOn}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* ── Body ── */}
        <div className="flex-1 overflow-y-auto px-6 sm:px-8 py-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">

          {/* ── Event Info ── */}
          <SectionCard title="Event Information" icon={<ClipboardList size={15} />} className="lg:col-span-2">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[
                ['Event Name',   s1?.eventName || event.title],
                ['Organizer',    event.organizerName || s1?.organizerDetails?.organizerName],
                ['Event Type',   s1?.eventType],
                ['Department',   s1?.organizerDetails?.department || 'CSE'],
                ['Date Range',   `${s1?.eventStartDate || '-'} to ${s1?.eventEndDate || '-'}`],
                ['Venue',        event.venue],
                ['IIC Activity', s1?.isIIC || 'No'],
                ['Prof. Societies', Array.isArray(s1?.professionalSocieties) && s1.professionalSocieties.length ? s1.professionalSocieties.join(', ') : '-'],
              ].map(([label, val]) => (
                <div key={label} className="rounded-xl border border-slate-100 bg-slate-50 px-3 py-2.5">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p>
                  <p className="text-sm font-semibold text-slate-800 mt-0.5">{val || '—'}</p>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* ── Attendance Summary — always shown ── */}
          <SectionCard title="Attendance Summary" icon={<Users size={15} />} accent="blue">
            {totalRegistered > 0 ? (
              <>
                <div className="grid grid-cols-3 gap-3 mb-4">
                  {[
                    { label: 'Registered', value: totalRegistered, color: 'bg-blue-50 text-blue-700' },
                    { label: 'Attended',   value: totalAttended,   color: 'bg-emerald-50 text-emerald-700' },
                    { label: 'No-Show',    value: Math.max(totalRegistered - totalAttended, 0), color: 'bg-amber-50 text-amber-700' },
                  ].map(({ label, value, color }) => (
                    <div key={label} className={`rounded-xl p-4 text-center ${color}`}>
                      <p className="text-3xl font-extrabold">{value}</p>
                      <p className="text-xs font-semibold mt-1 opacity-80">{label}</p>
                    </div>
                  ))}
                </div>
                <div className="mb-4">
                  <div className="flex justify-between text-xs font-semibold text-slate-500 mb-1">
                    <span>Attendance Rate</span>
                    <span className="text-emerald-600 font-bold">{attendancePct}%</span>
                  </div>
                  <div className="h-2.5 w-full rounded-full bg-slate-100 overflow-hidden">
                    <div className="h-full bg-emerald-500 rounded-full transition-all" style={{ width: `${attendancePct}%` }} />
                  </div>
                </div>
                <div className="rounded-xl border border-slate-100 overflow-hidden text-xs max-h-48 overflow-y-auto [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-slate-200 [&::-webkit-scrollbar-thumb]:rounded-full">
                  <table className="w-full">
                    <thead className="bg-slate-50 sticky top-0 z-10">
                      <tr>
                        {['Category', 'Registered', 'Attended', 'No-Show'].map(h => (
                          <th key={h} className="px-3 py-2 text-left font-bold text-slate-500 uppercase tracking-wide text-[10px]">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                      {[
                        ['Students', studentsCount, studentsAttended],
                        ['Faculty',  facultyCount,  facultyAttended],
                        ['External', externalCount, externalAttended],
                      ].map(([cat, r, att]) => (
                        <tr key={cat} className="hover:bg-slate-50">
                          <td className="px-3 py-2 font-semibold text-slate-700">{cat}</td>
                          <td className="px-3 py-2 text-slate-600">{r}</td>
                          <td className="px-3 py-2 text-emerald-600 font-semibold">{att}</td>
                          <td className="px-3 py-2 text-amber-600">{Math.max(Number(r) - Number(att), 0)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {reg.mode && <p className="mt-3 text-xs text-slate-500">Mode: <span className="font-semibold text-slate-700">{reg.mode}</span></p>}
              </>
            ) : (
              <p className="text-sm text-slate-400 italic flex-1 flex items-center">Attendance details were not recorded in this submission.</p>
            )}
          </SectionCard>

          {/* ── Student Attendance Roster — always shown ── */}
          <SectionCard title={`Student Attendance Roster${studentRoster.length > 0 ? ` (${studentRoster.length})` : ''}`} icon={<Users size={15} />} accent="indigo">
            {studentRoster.length > 0 ? (
              <div className="max-h-64 overflow-y-auto rounded-xl border border-slate-100 [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-slate-200 [&::-webkit-scrollbar-thumb]:rounded-full">
                <table className="w-full text-xs">
                  <thead className="sticky top-0 bg-slate-50 z-10 shadow-sm">
                    <tr>
                      {['#', 'Student', 'Roll No', 'Status'].map(h => (
                        <th key={h} className="px-3 py-2 text-left font-bold text-slate-500 uppercase tracking-wide text-[10px]">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-50">
                    {studentRoster.map((row, idx) => (
                      <tr key={row.id || idx} className="hover:bg-slate-50">
                        <td className="px-3 py-2 text-slate-400">{idx + 1}</td>
                        <td className="px-3 py-2 font-medium text-slate-800">{row.student || row.studentName || '—'}</td>
                        <td className="px-3 py-2 text-slate-500">{row.rollNo || '—'}</td>
                        <td className="px-3 py-2">
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold ${
                            row.attendanceStatus === 'NOT_ATTENDED' ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-700'
                          }`}>
                            {row.attendanceStatus === 'NOT_ATTENDED' ? '✗ Absent' : '✓ Present'}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-sm text-slate-400 italic flex-1 flex items-center">No student attendance roster was submitted.</p>
            )}
          </SectionCard>

          {/* ── Student Feedback — always shown ── */}
          <SectionCard title="Student Feedback" icon={<MessageSquare size={15} />} accent="purple">
            {autoFeedback?.totalResponses > 0 || studentFeedback.length > 0 ? (
              <>
                {autoFeedback && (
                  <div className="grid grid-cols-3 gap-3 mb-4">
                    {[
                      ['Responses',   autoFeedback.totalResponses ?? 0],
                      ['Avg. Rating', autoFeedback.averageRating   ?? '—'],
                      ['Out of',      autoFeedback.ratingOutOf     || 5],
                    ].map(([label, val]) => (
                      <div key={label} className="rounded-xl border border-purple-100 bg-purple-50 px-3 py-3 text-center">
                        <p className="text-2xl font-extrabold text-purple-700">{val}</p>
                        <p className="text-[10px] font-bold uppercase tracking-wider text-purple-500 mt-0.5">{label}</p>
                      </div>
                    ))}
                  </div>
                )}
                <div className="space-y-2 max-h-64 overflow-y-auto pr-2 pb-1 [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-slate-200 [&::-webkit-scrollbar-thumb]:rounded-full">
                  {(autoFeedback?.comments || studentFeedback).map((item, idx) => (
                    <div key={idx} className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3">
                      <div className="flex items-center justify-between flex-wrap gap-1">
                        <p className="text-sm font-semibold text-slate-800">
                          {item.student || item.name}{item.rollNo && <span className="text-xs text-slate-400 font-normal"> ({item.rollNo})</span>}
                        </p>
                        <span className="text-amber-500 text-sm">{'★'.repeat(Number(item.rating) || 5)}</span>
                      </div>
                      <p className={`text-xs mt-1 ${item.comment || item.feedback ? 'text-slate-600 italic' : 'text-slate-400'}`}>
                        {item.comment || item.feedback || 'No comment provided.'}
                      </p>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-400 italic flex-1 flex items-center">No student feedback has been submitted for this event yet.</p>
            )}
          </SectionCard>

          {/* ── Event Gallery — always shown ── */}
          <SectionCard title={`Event Gallery${gallery.length > 0 ? ` (${gallery.length} photos)` : ''}`} icon={<Star size={15} />} accent="amber">
            {gallery.length > 0 ? (
              <div className="flex flex-col flex-1">
                <div className="grid grid-cols-3 gap-2">
                  {gallery.map((img, i) => (
                    <div key={i} className="rounded-xl overflow-hidden aspect-square bg-slate-100 shadow-sm relative group">
                      <img src={img.url || img.dataUrl} alt={img.title || `Photo ${i + 1}`} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
                    </div>
                  ))}
                </div>
                {gallery.some(img => img.title) && (
                  <div className="mt-4 space-y-1.5 pt-4 border-t border-slate-100 max-h-[100px] overflow-y-auto">
                    {gallery.filter(img => img.title).map((img, i) => (
                      <p key={i} className="text-xs text-slate-500 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-slate-300"/> {img.title}</p>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <p className="text-sm text-slate-400 italic flex-1 flex items-center">No event photos were uploaded in this submission.</p>
            )}
          </SectionCard>

          {/* ── Resource Persons — always shown ── */}
          <SectionCard title={`Resource Persons / Speakers${resourcePersons.length > 0 ? ` (${resourcePersons.length})` : ''}`} icon={<Users size={15} />} accent="indigo" className="lg:col-span-2">
            {resourcePersons.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 max-h-60 overflow-y-auto pr-2 pb-1 [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-indigo-200 [&::-webkit-scrollbar-thumb]:rounded-full">
                {resourcePersons.map((rp, i) => (
                  <div key={i} className="rounded-xl border border-indigo-100 bg-indigo-50/40 px-4 py-3 flex flex-col justify-center">
                    <div className="flex items-start justify-between flex-wrap gap-2">
                      <div>
                        <p className="text-sm font-bold text-slate-800">{rp.name}</p>
                        {rp.designation && <p className="text-xs text-slate-500 mt-0.5">{rp.designation}{rp.organization ? ` · ${rp.organization}` : ''}</p>}
                        {rp.topic && <p className="text-xs text-indigo-600 mt-1.5 font-medium px-2 py-1 bg-indigo-100/50 rounded-md">Topic: {rp.topic}</p>}
                      </div>
                      {rp.rating && (
                        <div className="flex items-center gap-1 bg-white px-1.5 py-0.5 rounded shadow-sm border border-slate-100/50 mt-1">
                          {[1,2,3,4,5].map(s => (
                            <Star key={s} size={12} className={s <= (rp.rating || 5) ? 'text-amber-400 fill-amber-400' : 'text-slate-200 fill-slate-200'} />
                          ))}
                          <span className="text-[10px] font-bold text-amber-700 ml-0.5">{rp.rating}/5</span>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-400 italic">No resource persons were recorded in this submission.</p>
            )}
          </SectionCard>

          {/* ── Guest / Resource Person Feedback — always shown ── */}
          <SectionCard title="Guest / Resource Person Feedback" icon={<Star size={15} />} accent="amber" className="lg:col-span-2">
            {guestFeedback.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-h-60 overflow-y-auto pr-2 pb-1 [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-amber-200 [&::-webkit-scrollbar-thumb]:rounded-full">
                {guestFeedback.map((fb, i) => (
                  <div key={i} className="rounded-xl border border-amber-100 bg-amber-50/50 p-4">
                    <div className="flex items-center justify-between flex-wrap gap-2">
                      <div>
                        <p className="text-sm font-bold text-slate-800">{fb.name}</p>
                        {fb.designation && <p className="text-xs text-slate-500 mt-0.5">{fb.designation}{fb.organization ? ` · ${fb.organization}` : ''}</p>}
                      </div>
                      <div className="flex items-center gap-1 bg-white px-2 py-1 rounded shadow-sm">
                        {[1,2,3,4,5].map(s => (
                          <Star key={s} size={12} className={s <= (fb.rating || 5) ? 'text-amber-400 fill-amber-400' : 'text-slate-200 fill-slate-200'} />
                        ))}
                        <span className="text-[10px] font-bold text-amber-700 ml-1">{fb.rating || 5}/5</span>
                      </div>
                    </div>
                    {fb.feedback && <p className="mt-3 text-sm text-slate-700 italic border-l-[3px] border-amber-300 pl-3">"{fb.feedback}"</p>}
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-400 italic">No guest or resource person feedback was recorded.</p>
            )}
          </SectionCard>

          {/* ── Documentation Checklist — always shown ── */}
          <SectionCard title="Documentation Checklist" icon={<FileCheck size={15} />} accent="emerald" className="lg:col-span-2 shadow-md">
            {checklist.length > 0 ? (
              <>
                <div className="space-y-2">
                  {checklist.map((item) => {
                    const dlAction = getDownloadAction(item);
                    return (
                      <div key={item.id} className="flex items-center gap-3 px-3 py-2.5 rounded-xl border border-slate-100 bg-slate-50 hover:bg-slate-100 transition-colors">
                        <span className={`w-5 h-5 rounded-full flex items-center justify-center shrink-0 text-[11px] font-bold ${checklistStatusColor(item.status)}`}>
                          {item.status === 'pending' ? '✗' : '✓'}
                        </span>
                        <span className="flex-1 text-sm text-slate-700 font-medium">{item.requirement}</span>
                        <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full ${checklistStatusColor(item.status)}`}>
                          {checklistStatusLabel(item.status)}
                        </span>
                        {dlAction && (
                          <button
                            onClick={(e) => { e.stopPropagation(); dlAction(); }}
                            title={`Download ${item.requirement}`}
                            className="ml-1 inline-flex items-center gap-1 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white px-2.5 py-1 text-[10px] font-bold transition-colors"
                          >
                            <Download size={11} /> Download
                          </button>
                        )}
                      </div>
                    );
                  })}
                </div>
                <div className="mt-4 pt-4 border-t border-slate-100 flex items-center gap-3">
                  <div className="flex-1 h-2 rounded-full bg-slate-100 overflow-hidden">
                    <div className="h-full bg-emerald-500 rounded-full transition-all"
                      style={{ width: `${Math.round((checklist.filter(c => c.status !== 'pending').length / checklist.length) * 100)}%` }} />
                  </div>
                  <span className="text-xs font-bold text-emerald-600 shrink-0">
                    {checklist.filter(c => c.status !== 'pending').length}/{checklist.length} Complete
                  </span>
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-400 italic">No documentation checklist was recorded in this submission.</p>
            )}
          </SectionCard>
          </div>
          
          {/* ── Footer ── */}
          {submittedOn && (
            <div className="mt-8 text-center text-xs text-slate-400">
              This IQAC report was submitted on <span className="font-semibold text-slate-500">{submittedOn}</span> by the event organizer.
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

// ── EventCard — module-level so React never sees a new component type on re-renders ──
const EventCard = ({
  event, currentUser, odRequests, processingEventId,
  getEventStatus, isRegistered, canDownloadOD, canSubmitFeedback,
  onRegister, onWithdraw, onDownloadOD, onOpenFeedback, onOpenIQAC,
  defaultPoster,
}) => {
  const status = getEventStatus(event);
  // Treat as completed if date-computed status OR Firestore status says so
  const isCompleted = status === 'completed' || String(event.status || '').toUpperCase() === 'COMPLETED';
  const isUpcoming = !isCompleted && status === 'upcoming';
  const registered = isRegistered(event);
  const processing = processingEventId === event.id;
  const isStudent = currentUser?.role === UserRole.STUDENT_GENERAL || currentUser?.role === UserRole.STUDENT_ORGANIZER;
  const showOD = canDownloadOD(event);
  const showFeedback = canSubmitFeedback(event);
  const showIQAC = isCompleted && (event.iqacSubmittedAt || event.iqacSubmission);
  const odReq = odRequests.find(r => r.eventId === event.id && r.studentId === currentUser?.id && r.status !== 'WITHDRAWN');
  const requestStatus = odReq ? odReq.status : null;

  return (
    <div
      onClick={() => showIQAC && onOpenIQAC(event)}
      className={`bg-white rounded-xl shadow-md overflow-hidden transition-shadow duration-200 ${showIQAC ? 'hover:shadow-xl cursor-pointer' : 'cursor-default'}`}
    >
      <div className="h-48 overflow-hidden">
        <img
          src={event.posterDataUrl || event.posterUrl || defaultPoster}
          alt={event.title || event.requisition?.step1?.eventName || 'Event'}
          className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
        />
      </div>
      <div className="p-5">
        <div className="flex items-start justify-between mb-3">
          <h3 className="text-lg font-bold text-slate-900 line-clamp-2 flex-1">
            {event.title || event.requisition?.step1?.eventName || 'Untitled Event'}
          </h3>
          <span className={`ml-2 px-2.5 py-1 rounded-full text-xs font-semibold whitespace-nowrap ${
            status === 'upcoming' ? 'bg-blue-100 text-blue-700' :
            status === 'ongoing'  ? 'bg-green-100 text-green-700' :
            'bg-gray-100 text-gray-700'
          }`}>
            {status.toUpperCase()}
          </span>
        </div>

        <div className="space-y-2 mb-4">
          <div className="flex items-center gap-2 mb-3">
             <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
               event.creatorType === 'FACULTY' ? 'bg-purple-100 text-purple-700 border border-purple-200' : 'bg-indigo-100 text-indigo-700 border border-indigo-200'
             }`}>
               {event.creatorType === 'FACULTY' ? 'Faculty Event' : 'Student Event'}
             </span>
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-600">
            <Calendar size={14} />
            <span className="text-xs">{event.requisition?.step1?.eventStartDate} to {event.requisition?.step1?.eventEndDate}</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-600">
            <Clock size={14} />
            <span className="text-xs">{event.requisition?.step1?.eventStartTime} - {event.requisition?.step1?.eventEndTime}</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-600">
            <MapPin size={14} />
            <span className="text-xs">{event.venue || 'Venue TBA'}</span>
          </div>
        </div>

        {event.requisition?.step1?.eventDescription && (
          <p className="text-xs text-slate-600 mb-4 line-clamp-2">{event.requisition.step1.eventDescription}</p>
        )}

        {showIQAC && (
          <div className="mb-3 p-2.5 bg-green-50 border border-green-200 rounded-lg">
            <div className="flex items-center gap-2 text-green-700 text-xs font-semibold">
              <FileCheck size={14} /><span>IQAC Submitted</span>
            </div>
          </div>
        )}

        <div className="flex flex-wrap gap-2">
          {/* Register — only upcoming, only non-organizers */}
          {isStudent && !registered && isUpcoming && event.organizerId !== currentUser?.id && (
            <button onClick={(e) => { e.stopPropagation(); onRegister(event.id); }} disabled={processing}
              className="flex items-center gap-1.5 px-3 py-2 bg-cse-accent text-white rounded-lg hover:bg-cse-accent/90 disabled:opacity-50 text-xs font-medium">
              {processing ? <Loader2 size={14} className="animate-spin" /> : <UserPlus size={14} />} Register
            </button>
          )}
          {/* Withdraw — only upcoming (once event starts, no withdrawal) */}
          {isStudent && registered && isUpcoming && (
            <button onClick={(e) => { e.stopPropagation(); onWithdraw(event.id); }} disabled={processing}
              className="flex items-center gap-1.5 px-3 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 disabled:opacity-50 text-xs font-medium">
              {processing ? <Loader2 size={14} className="animate-spin" /> : <UserMinus size={14} />} Withdraw
            </button>
          )}
          {/* Registration status badges — only on upcoming events */}
          {isStudent && registered && isUpcoming && requestStatus === 'APPROVED' && (
            <span className="flex items-center gap-1.5 px-3 py-2 bg-green-100 text-green-700 rounded-lg text-xs font-medium">
              <CheckCircle size={14} /> Registered (Approved)
            </span>
          )}
          {isStudent && registered && isUpcoming && requestStatus === 'PENDING_ORGANIZER' && (
            <span className="flex items-center gap-1.5 px-3 py-2 bg-yellow-100 text-yellow-700 rounded-lg text-xs font-medium">
              <Clock size={14} /> Pending Approval
            </span>
          )}
          {isStudent && registered && isUpcoming && requestStatus === 'REJECTED' && (
            <span className="flex items-center gap-1.5 px-3 py-2 bg-red-100 text-red-700 rounded-lg text-xs font-medium">
              <XCircle size={14} /> Registration Rejected
            </span>
          )}
          {isStudent && registered && isUpcoming && !requestStatus && (
            <span className="flex items-center gap-1.5 px-3 py-2 bg-green-100 text-green-700 rounded-lg text-xs font-medium">
              <CheckCircle size={14} /> Registered
            </span>
          )}
          {/* OD Letter — only on upcoming events (before event starts) */}
          {showOD && isUpcoming && (
            <button onClick={(e) => { e.stopPropagation(); onDownloadOD(event); }}
              className="flex items-center gap-1.5 px-3 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 text-xs font-medium">
              <Download size={14} /> OD Letter
            </button>
          )}
          {/* Feedback — only on completed events for registered students */}
          {showFeedback && isCompleted && (
            <button onClick={(e) => { e.stopPropagation(); onOpenFeedback(event); }}
              className="flex items-center gap-1.5 px-3 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 text-xs font-medium">
              <MessageSquare size={14} /> Feedback
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

const ExploreEvents = () => {
  const { currentUser, odRequests = [] } = useAppContext();
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [showODModal, setShowODModal] = useState(false);
  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [showEventDetail, setShowEventDetail] = useState(false);
  const [processingEventId, setProcessingEventId] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    loadEvents();
  }, []);

  const loadEvents = async (silent = false) => {
    try {
      if (!silent) setLoading(true);
      const allEvents = await fetchEvents();
      // Show both POSTED and COMPLETED events in the explore page
      const visibleEvents = allEvents.filter(
        e => e.status === EventStatus.POSTED || e.status === EventStatus.COMPLETED
      );
      setEvents(visibleEvents);
    } catch (error) {
      console.error('Error loading events:', error);
    } finally {
      if (!silent) setLoading(false);
    }
  };

  const getEventStatus = (event) => {
    const now = Date.now();
    const startDate = event.requisition?.step1?.eventStartDate;
    const startTime = event.requisition?.step1?.eventStartTime || '00:00';
    const endDate = event.requisition?.step1?.eventEndDate;
    const endTime = event.requisition?.step1?.eventEndTime || '23:59';

    if (!startDate || !endDate) return 'upcoming';

    const start = new Date(`${startDate}T${startTime}`).getTime();
    const end = new Date(`${endDate}T${endTime}`).getTime();

    if (now < start) return 'upcoming';
    if (now >= start && now <= end) return 'ongoing';
    return 'completed';
  };

  const filteredEvents = useMemo(() => {
    if (filter === 'all') return events;
    return events.filter(e => getEventStatus(e) === filter);
  }, [events, filter]);

  const isRegistered = (event) => {
    return event.registeredStudents?.some(s => s.userId === currentUser?.id);
  };

  const handleRegister = async (eventId) => {
    if (!currentUser) return;
    setProcessingEventId(eventId);

    // Build the registration entry we'll add locally
    const newEntry = {
      userId: currentUser.id,
      userName: currentUser.name,
      userEmail: currentUser.email || '',
      userDepartment: currentUser.department || '',
      userYear: currentUser.year || '',
      rollNo: currentUser.rollNo || currentUser.password || '',
      userClass: currentUser.class || currentUser.className || '',
      registeredAt: new Date().toISOString(),
    };

    // Optimistic update — add student to local state immediately (no blink)
    setEvents(prev => prev.map(ev =>
      ev.id === eventId
        ? { ...ev, registeredStudents: [...(ev.registeredStudents || []), newEntry] }
        : ev
    ));

    try {
      // 1. Create OD Request
      await fetch(`http://localhost:5001/api/od-requests`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          eventId,
          studentId: currentUser.id,
          studentName: currentUser.name,
          rollNo: currentUser.rollNo || currentUser.password || '',
          class: currentUser.class || currentUser.className || '',
          email: currentUser.email,
          registrationType: 'PARTICIPANT'
        }),
      });

      // 2. Persist registration to Firestore
      const response = await fetch(`http://localhost:5001/api/events/${eventId}/register`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newEntry),
      });

      // 409 = already registered in Firestore — optimistic state is already correct, carry on
      if (!response.ok && response.status !== 409) {
        // Roll back optimistic update on unexpected failure
        setEvents(prev => prev.map(ev =>
          ev.id === eventId
            ? { ...ev, registeredStudents: (ev.registeredStudents || []).filter(s => s.userId !== currentUser.id) }
            : ev
        ));
      }
    } catch (error) {
      console.error('Error registering:', error);
      // Roll back on network failure
      setEvents(prev => prev.map(ev =>
        ev.id === eventId
          ? { ...ev, registeredStudents: (ev.registeredStudents || []).filter(s => s.userId !== currentUser.id) }
          : ev
      ));
    } finally {
      setProcessingEventId(null);
    }
  };

  const handleWithdraw = async (eventId) => {
    if (!currentUser) return;
    setProcessingEventId(eventId);

    // Optimistic update — remove student from local state immediately (no blink)
    setEvents(prev => prev.map(ev =>
      ev.id === eventId
        ? { ...ev, registeredStudents: (ev.registeredStudents || []).filter(s => s.userId !== currentUser.id) }
        : ev
    ));

    try {
      // Withdraw OD request if one exists
      const odReq = odRequests.find(r => r.eventId === eventId && r.studentId === currentUser.id && r.status !== 'WITHDRAWN');
      if (odReq) {
        await fetch(`http://localhost:5001/api/od-requests/${odReq.id}/withdraw`, { method: 'PATCH' });
      }

      await fetch(`http://localhost:5001/api/events/${eventId}/withdraw`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: currentUser.id }),
      });
    } catch (error) {
      console.error('Error withdrawing:', error);
      // Roll back optimistic update on failure
      loadEvents(true);
    } finally {
      setProcessingEventId(null);
    }
  };

  const handleDownloadOD = (event) => {
    setSelectedEvent(event);
    setShowODModal(true);
  };

  const canDownloadOD = (event) => {
    if (!isRegistered(event)) return false;
    // Check if there is an APPROVED OD Request
    const odReq = odRequests.find(r => r.eventId === event.id && r.studentId === currentUser?.id);
    if (!odReq || odReq.status !== 'APPROVED') return false;

    const startDate = event.requisition?.step1?.eventStartDate;
    const startTime = event.requisition?.step1?.eventStartTime || '00:00';
    if (!startDate) return false;
    const start = new Date(`${startDate}T${startTime}`).getTime();
    const twentyFourHoursBefore = start - (24 * 60 * 60 * 1000); 
    return Date.now() >= twentyFourHoursBefore;
  };

  const canSubmitFeedback = (event) => {
    // Must be registered
    if (!isRegistered(event)) return false;

    // Block if feedback already submitted or registration rejected (check any non-withdrawn OD request)
    const odReq = odRequests.find(r => r.eventId === event.id && r.studentId === currentUser?.id && r.status !== 'WITHDRAWN');
    if (!odReq || odReq.status === 'REJECTED' || odReq.feedback) return false;

    const endDate = event.requisition?.step1?.eventEndDate;
    const endTime = event.requisition?.step1?.eventEndTime || '23:59';
    if (!endDate) return false;

    const end = new Date(`${endDate}T${endTime}`).getTime();
    const now = Date.now();
    const sevenDaysAfter = end + (7 * 24 * 60 * 60 * 1000); // 7 days after event ends

    // Show feedback button once event has ended and within 7 days
    return now >= end && now <= sevenDaysAfter;
  };
  // Shared props for the stable module-level EventCard
  const cardSharedProps = {
    currentUser, odRequests, processingEventId,
    getEventStatus, isRegistered, canDownloadOD, canSubmitFeedback,
    onRegister: handleRegister,
    onWithdraw: handleWithdraw,
    onDownloadOD: handleDownloadOD,
    onOpenFeedback: (event) => { setSelectedEvent(event); setShowFeedbackModal(true); },
    onOpenIQAC: (event) => { setSelectedEvent(event); setShowEventDetail(true); },
    defaultPoster,
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <Navbar />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">Explore Events</h1>
            <p className="text-slate-600">Discover and register for upcoming events</p>
          </div>
          <button onClick={() => navigate('/dashboard')} className="btn-secondary whitespace-nowrap">
            Back to Dashboard
          </button>
        </div>

        <div className="flex gap-3 mb-6 overflow-x-auto pb-2">
          {['all', 'upcoming', 'ongoing', 'completed'].map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-6 py-2 rounded-lg font-medium whitespace-nowrap transition-colors ${
                filter === f
                  ? 'bg-cse-accent text-white'
                  : 'bg-white text-slate-700 hover:bg-slate-100'
              }`}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
              <span className="ml-2 text-sm opacity-75">
                ({f === 'all' ? events.length : events.filter(e => getEventStatus(e) === f).length})
              </span>
            </button>
          ))}
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 size={40} className="animate-spin text-cse-accent" />
          </div>
        ) : filteredEvents.length === 0 ? (
          <div className="text-center py-20">
            <XCircle size={48} className="mx-auto text-slate-300 mb-4" />
            <h3 className="text-xl font-semibold text-slate-700 mb-2">No events found</h3>
            <p className="text-slate-500">There are no {filter !== 'all' ? filter : ''} events at the moment.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredEvents.map((event) => (
                <EventCard key={event.id} event={event} {...cardSharedProps} />
              ))}
            </div>
        )}
      </div>

      {showODModal && selectedEvent && (
        <ODLetterModal
          odRequest={odRequests.find(r => r.eventId === selectedEvent.id && r.studentId === currentUser?.id && r.status === 'APPROVED')}
          onClose={() => {
            setShowODModal(false);
            setSelectedEvent(null);
          }}
        />
      )}

      {showFeedbackModal && selectedEvent && (() => {
        const odReq = odRequests.find(r => r.eventId === selectedEvent.id && r.studentId === currentUser?.id && r.status === 'APPROVED');
        return odReq ? (
          <FeedbackModal
            odRequestId={odReq.id}
            eventTitle={selectedEvent.title || selectedEvent.requisition?.step1?.eventName || 'Event'}
            onClose={() => {
              setShowFeedbackModal(false);
              setSelectedEvent(null);
            }}
          />
        ) : null;
      })()}

      <AnimatePresence>
        {showEventDetail && selectedEvent && (
          <IQACSummaryModal
            event={selectedEvent}
            onClose={() => {
              setShowEventDetail(false);
              setSelectedEvent(null);
            }}
          />
        )}
      </AnimatePresence>
    </div>
  );
};

export default ExploreEvents;
