import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import defaultPoster from '../assets/sece.avif';
import { AlertCircle, CheckCircle2, FileCheck2, Loader2, Upload, X, Plus, Star, FileText, Camera, FileUp, Check, Circle, LayoutGrid, Globe } from 'lucide-react';
import Navbar from '../components/Navbar';
import { useAppContext } from '../context/AppContext';
import { EventStatus } from '../types';
import EventReportModal from '../components/EventReportModal';
import * as XLSX from 'xlsx';

const formatTime12 = (t24) => {
  if (!t24) return "-";
  try {
    const [h, m] = String(t24).split(':');
    const hh = parseInt(h, 10);
    const suffix = hh >= 12 ? 'PM' : 'AM';
    const h12 = hh % 12 || 12;
    return `${h12.toString().padStart(2, '0')}:${m} ${suffix}`;
  } catch (e) {
    return t24;
  }
};

const SDG_NAMES = {
  1: "No Poverty",
  2: "Zero Hunger",
  3: "Good Health and Well-being",
  4: "Quality Education",
  5: "Gender Equality",
  6: "Clean Water and Sanitation",
  7: "Affordable and Clean Energy",
  8: "Decent Work and Economic Growth",
  9: "Industry, Innovation and Infrastructure",
  10: "Reduced Inequality",
  11: "Sustainable Cities and Communities",
  12: "Responsible Consumption and Production",
  13: "Climate Action",
  14: "Life Below Water",
  15: "Life on Land",
  16: "Peace, Justice and Strong Institutions",
  17: "Partnerships for the Goals"
};

const CHECKLIST_ITEMS = [
  { id: 'requisition-letter-hod', label: 'Requisition Letter to HoD', autoGenerated: true },
  { id: 'food-transport-requisition', label: 'Food / Transport Requisition Letter' },
  { id: 'financial-assistance-letter', label: 'Financial Assistance Letter (Optional)' },
  { id: 'letter-to-resource-person', label: 'Letter to Resource Person' },
  { id: 'acceptance-mail-resource-person', label: 'Acceptance Mail from Resource Person' },
  { id: 'event-brochure-flyer', label: 'Event Brochure / Flyer', autoGenerated: true },
  { id: 'event-schedule', label: 'Event Schedule', autoGenerated: true },
  { id: 'invitation-copy', label: 'Invitation Copy' },
  { id: 'cv-resource-person', label: 'CV of Resource Person' },
  { id: 'attendance-sheet', label: 'Attendance Sheet', autoGenerated: true },
  { id: 'feedback-resource-person', label: 'Feedback from Resource Person', autoGenerated: true },
  { id: 'feedback-participants', label: 'Feedback from Participants', autoGenerated: true },
  { id: 'event-report', label: 'Event Report', autoGenerated: true },
  { id: 'geotagged-photos', label: 'Geotagged Photos', autoGenerated: true },
  { id: 'certificates-issued', label: 'Certificates Issued' },
  { id: 'account-settlement-bills', label: 'Account Settlement / Bills (Optional)' },
  { id: 'press-media-materials', label: 'Press / Media Materials (Optional)' },
];

const ACCEPTED_TYPES = '.pdf,.doc,.docx,.jpg,.jpeg,.png';
const MAX_DOC_SIZE = 250 * 1024; // 250 KB in bytes
const MAX_DOC_SIZE_LABEL = '250 KB';

const STATUS_THEME = {
  pending: 'bg-red-50 text-red-700 border border-red-200',
  uploaded: 'bg-blue-50 text-blue-700 border border-blue-200',
  autoGenerated: 'bg-slate-100 text-slate-700 border border-slate-200',
  verified: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
};

const toDateRange = (event) => {
  const start = event?.requisition?.step1?.eventStartDate || event?.date || '-';
  const end = event?.requisition?.step1?.eventEndDate || event?.date || '-';
  const startTime = event?.requisition?.step1?.eventStartTime || event?.startTime || '';
  const endTime = event?.requisition?.step1?.eventEndTime || event?.endTime || '';

  let range = (start === end || end === '-') ? start : `${start} - ${end}`;
  if (startTime && endTime) {
    range += ` (${formatTime12(startTime)} - ${formatTime12(endTime)})`;
  }
  return range;
};

const yesNo = (value) => (String(value || '').toLowerCase() === 'yes' ? 'Yes' : 'No');

const isEventEndTimePassed = (event) => {
  if (!event) return false;
  const eventDate = event.date || event.requisition?.step1?.eventStartDate;
  const endTime = event.endTime || event.requisition?.step1?.eventEndTime;
  if (!eventDate || !endTime) return false;

  const [hours, minutes] = String(endTime).split(':').map(Number);
  const eventEnd = new Date(eventDate);
  eventEnd.setHours(hours, minutes, 0, 0);

  const now = Date.now();
  const endMs = eventEnd.getTime();
  const sevenDaysAfter = endMs + (7 * 24 * 60 * 60 * 1000);

  // Must be after event end AND within 7 days
  return now > endMs && now <= sevenDaysAfter;
};

const StatusBadge = ({ status }) => {
  const labelMap = {
    pending: 'Pending',
    uploaded: 'Uploaded',
    autoGenerated: 'Auto Generated',
    verified: 'Verified',
  };

  return (
    <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${STATUS_THEME[status]}`}>
      {labelMap[status]}
    </span>
  );
};

const IQACSubmission = () => {
  const { currentUser, selectedEvent, odRequests = [] } = useAppContext();
  const navigate = useNavigate();

  const [uploads, setUploads] = useState({});
  const [uploadErrors, setUploadErrors] = useState({});
  const [verified, setVerified] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [validationError, setValidationError] = useState('');

  // New state for gallery, guest feedback, and registration details
  const [gallery, setGallery] = useState([]);
  const [guestFeedback, setGuestFeedback] = useState([]);
  const [registrationDetails, setRegistrationDetails] = useState({
    studentsCount: 0,
    facultyCount: 0,
    externalCount: 0,
    studentsAttended: 0,
    facultyAttended: 0,
    externalAttended: 0,
    periodStart: '',
    periodEnd: '',
    mode: 'Hybrid',
    venue: '',
  });
  const [isFetchingStats, setIsFetchingStats] = useState(false);
  const [autoAttendanceStats, setAutoAttendanceStats] = useState(null);
  const [autoFeedbackSummary, setAutoFeedbackSummary] = useState(null);
  const [studentAttendanceRoster, setStudentAttendanceRoster] = useState([]);
  const [eventOutcome, setEventOutcome] = useState('');

  // Detailed Report Content State
  const [reportDetails, setReportDetails] = useState({
    objectives: [
      ''
    ],
    description: '',
    outcomes: [
      ''
    ],
    benefits: {
      technical: '',
      industry: ''
    },
    socialMedia: {
      website: '',
      social: ''
    },
    mapping: {
      sdg: '4',
      po: '1, 3, 5, 8, 9, 12',
      pso: '1, 2'
    }
  });

  // Resource persons state
  const [resourcePersons, setResourcePersons] = useState([]);
  const [resourcePersonForm, setResourcePersonForm] = useState({
    name: '',
    designation: '',
    organization: '',
    topicsByDay: [],
    email: '',
    phone: '',
    expertise: '',
    bio: '',
    photo: null,
  });

  const today = new Date().toISOString().split('T')[0];

  const [showReportModal, setShowReportModal] = useState(false);

  useEffect(() => {
    if (!currentUser) {
      navigate('/');
      return;
    }
    if (!selectedEvent) {
      navigate('/dashboard');
      return;
    }

    // Fetch OD request stats to auto-populate registration details
    const fetchODStats = async () => {
      try {
        setIsFetchingStats(true);
        const response = await fetch(`http://localhost:5001/api/iqac/${selectedEvent.id}`);
        const data = await response.json();

        if (data.success) {
          const { attendanceStats = null, feedbackSummary = null, iqacData = null } = data;
          const savedStudentAttendance = iqacData?.registration?.attendance?.studentAttendanceList || [];

          setAutoAttendanceStats(attendanceStats);
          setAutoFeedbackSummary(feedbackSummary);

          // Populate saved data if exists
          if (iqacData) {
            if (iqacData.gallery) setGallery(iqacData.gallery.map((g, i) => ({ ...g, id: g.id || `saved-g-${i}`, dataUrl: g.dataUrl || g.url })));
            if (iqacData.resourcePersons) setResourcePersons(iqacData.resourcePersons.map((rp, i) => ({ ...rp, id: rp.id || `saved-rp-${i}` })));
            if (iqacData.guestFeedback) setGuestFeedback(iqacData.guestFeedback.map((gf, i) => ({ ...gf, id: gf.id || `saved-gf-${i}`, highlights: Array.isArray(gf.highlights) ? gf.highlights.join(', ') : gf.highlights })));
            if (iqacData.eventOutcome) setEventOutcome(iqacData.eventOutcome);

            if (iqacData.reportDetails) {
              setReportDetails(prev => ({ ...prev, ...iqacData.reportDetails }));
            }

            if (iqacData.registration) {
              setRegistrationDetails({
                studentsCount: iqacData.registration.categories?.students || 0,
                facultyCount: iqacData.registration.categories?.faculty || 0,
                externalCount: iqacData.registration.categories?.external || 0,
                studentsAttended: iqacData.registration.attendance?.categories?.students || 0,
                facultyAttended: iqacData.registration.attendance?.categories?.faculty || 0,
                externalAttended: iqacData.registration.attendance?.categories?.external || 0,
                periodStart: iqacData.registration.period?.start || '',
                periodEnd: iqacData.registration.period?.end || '',
                mode: iqacData.registration.mode || 'Hybrid',
              });
            }

            if (iqacData.documents) {
              const nextUploads = {};
              const nextVerified = {};
              Object.entries(iqacData.documents).forEach(([label, doc]) => {
                const item = CHECKLIST_ITEMS.find(i => i.label === label);
                if (item) {
                  if (!doc.autoGenerated) nextUploads[item.id] = doc;
                  if (doc.verified) nextVerified[item.id] = true;
                }
              });
              setUploads(nextUploads);
              setVerified(nextVerified);
            }
          }

          if (attendanceStats) {
            const rows = Array.isArray(attendanceStats.rows) ? attendanceStats.rows : [];
            let nextRoster = [];

            if (Array.isArray(savedStudentAttendance) && savedStudentAttendance.length > 0) {
              nextRoster = savedStudentAttendance.map((item, idx) => ({
                id: item.id || item.requestId || item.rollNo || `saved-${idx + 1}`,
                requestId: item.requestId || item.id || '',
                student: item.student || item.studentName || '',
                rollNo: item.rollNo || '',
                attendanceStatus: String(item.attendanceStatus || item.status || 'ATTENDED').toUpperCase() === 'NOT_ATTENDED'
                  ? 'NOT_ATTENDED'
                  : 'ATTENDED',
              }));
            } else {
              nextRoster = rows.map((row, idx) => {
                const baseRow = {
                  id: row.id || row.requestId || row.rollNo || `row-${idx + 1}`,
                  requestId: row.id || row.requestId || '',
                  student: row.student || '',
                  rollNo: row.rollNo || '',
                };
                const n = selectedEvent.requisition?.step1?.numberOfDays || 1;
                for (let d = 1; d <= n; d++) { baseRow[`day${d}`] = 'ATTENDED'; }
                return baseRow;
              });
            }

            setStudentAttendanceRoster(nextRoster);

            if (!iqacData) {
              const studentsRegisteredFromRoster = nextRoster.length;
              const studentsAttendedFromRoster = nextRoster.filter((item) => item.attendanceStatus === 'ATTENDED').length;

              const s1 = selectedEvent.requisition?.step1;
              setRegistrationDetails((prev) => ({
                ...prev,
                studentsCount: studentsRegisteredFromRoster || attendanceStats.totalRegistered || 0,
                studentsAttended: studentsAttendedFromRoster || attendanceStats.totalRegistered || 0,
                periodStart: s1?.eventStartDate || selectedEvent.date || '',
                periodEnd: s1?.eventEndDate || selectedEvent.date || '',
                mode: s1?.registrationMode || 'In-person',
                venue: selectedEvent.venue || ''
              }));
            }
          }
        }
      } catch (error) {
        console.error('Failed to fetch OD stats:', error);
      } finally {
        setIsFetchingStats(false);
      }
    };

    fetchODStats();
  }, [currentUser, selectedEvent, navigate]);

  // Effect to fetch student feedbacks into Guest Feedback section
  useEffect(() => {
    if (!selectedEvent || !odRequests.length) return;

    // Only auto-fetch if we haven't already or if we want to refresh
    const studentFeedbacks = odRequests
      .filter(r => r.eventId === selectedEvent.id && (r.feedback || r.studentFeedback))
      .map(r => {
        // Handle both old and new feedback formats
        const rawFeedback = r.feedback || r.studentFeedback;
        const comment = typeof rawFeedback === 'object' ? rawFeedback.comment : rawFeedback;

        return {
          id: `auto-${r.id}`,
          name: r.studentName || 'Student',
          designation: 'Participant (Student)',
          organization: r.class || r.department || 'Internal',
          feedback: comment || 'No comments provided',
          isAutoFetched: true
        };
      });

    if (studentFeedbacks.length > 0) {
      setGuestFeedback(prev => {
        // Keep manual entries, but refresh auto-fetched ones
        const manual = prev.filter(f => !f.isAutoFetched);
        // Avoid adding the same IDs again
        const next = [...manual, ...studentFeedbacks];
        // Deduplicate by ID
        return Array.from(new Map(next.map(item => [item.id, item])).values());
      });
    }
  }, [selectedEvent, odRequests]);

  const eligibleForIQAC = useMemo(() => {
    if (!selectedEvent) return false;
    const isApprovedStatus = selectedEvent.status === EventStatus.COMPLETED || selectedEvent.status === EventStatus.POSTED;
    
    // If it's extended properly and not yet past 2 days
    if (selectedEvent.iqacWindowExtended) {
      if (!selectedEvent.iqacWindowExtendedAt) return isApprovedStatus; // Legacy events
      const extEndMs = new Date(selectedEvent.iqacWindowExtendedAt).getTime() + (2 * 24 * 60 * 60 * 1000);
      if (Date.now() <= extEndMs) return isApprovedStatus;
    }
    
    // Default 7-day window check
    const isEventEnded = isEventEndTimePassed(selectedEvent);
    return isApprovedStatus && isEventEnded;
  }, [selectedEvent]);

  const hasStudentRoster = studentAttendanceRoster.length > 0;
  const numberOfDays = selectedEvent?.requisition?.step1?.numberOfDays || 1;
  const studentsRegisteredFromRoster = studentAttendanceRoster.length;
  const studentsAttendedFromRoster = studentAttendanceRoster.reduce((total, item) => {
    let studentScore = 0;
    let hasDayRecords = false;
    for (let i = 1; i <= numberOfDays; i++) {
      if (item[`day${i}`]) {
        hasDayRecords = true;
        if (item[`day${i}`] === 'ATTENDED') studentScore += 1;
        else if (item[`day${i}`] === 'FN' || item[`day${i}`] === 'AN') studentScore += 0.5;
      }
    }
    
    if (!hasDayRecords) {
      if (item.attendanceStatus === 'ATTENDED') studentScore += 1;
      else if (item.attendanceStatus === 'FN' || item.attendanceStatus === 'AN') studentScore += 0.5;
    } else if (numberOfDays > 0) {
      studentScore = studentScore / numberOfDays;
    }
    return total + studentScore;
  }, 0);
  const studentsNoShowFromRoster = Math.max(studentsRegisteredFromRoster - studentsAttendedFromRoster, 0);
  const studentAttendancePercent = studentsRegisteredFromRoster > 0
    ? `${Math.round((studentsAttendedFromRoster / studentsRegisteredFromRoster) * 100)}%`
    : '0%';

  const progressStats = useMemo(() => {
    const sections = [
      {
        id: 'registration',
        label: 'Registration Details',
        isComplete: Boolean(registrationDetails.mode && registrationDetails.periodStart && registrationDetails.periodEnd && (Number(registrationDetails.studentsAttended) > 0 || hasStudentRoster))
      },
      {
        id: 'documents',
        label: 'Required Documents',
        isComplete: CHECKLIST_ITEMS.every(item => item.autoGenerated || item.label.toLowerCase().includes('(optional)') || !!uploads[item.id])
      },
      {
        id: 'student-feedback',
        label: 'Student Feedback (CSV)',
        isComplete: Boolean(autoFeedbackSummary?.totalResponses > 0)
      },
      {
        id: 'report-content',
        label: 'Academic Report Content',
        isComplete: Boolean(
          reportDetails.description &&
          reportDetails.objectives.length > 0 &&
          reportDetails.outcomes.length > 0 &&
          reportDetails.benefits?.technical &&
          reportDetails.benefits?.industry &&
          reportDetails.mapping?.sdg &&
          reportDetails.mapping?.po
        )
      },
      {
        id: 'resource-persons',
        label: 'Resource Persons',
        isComplete: resourcePersons.length > 0
      },
      {
        id: 'guest-feedback',
        label: 'Guest Feedback (CSV)',
        isComplete: guestFeedback.length > 0
      },
      {
        id: 'gallery',
        label: 'Event Gallery (Photos)',
        isComplete: gallery.length > 0
      }
    ];

    const completedCount = sections.filter(s => s.isComplete).length;
    const progressPercent = Math.round((completedCount / (sections.length || 1)) * 100);

    return { sections, completedCount, totalCount: sections.length, progressPercent };
  }, [registrationDetails, uploads, autoFeedbackSummary, reportDetails, resourcePersons, guestFeedback, gallery, hasStudentRoster]);

  const eventInfo = useMemo(() => {
    if (!selectedEvent) return null;
    const step1 = selectedEvent.requisition?.step1;

    return {
      title: selectedEvent.title || step1?.eventName || '-',
      organizerName: selectedEvent.organizerName || step1?.organizerDetails?.organizerName || '-',
      department: step1?.organizerDetails?.department || selectedEvent.department || 'Computer Science and Engineering',
      eventType: selectedEvent.eventType || step1?.eventType || '-',
      eventDate: toDateRange(selectedEvent),
      venue: selectedEvent.venue && selectedEvent.venue !== 'To be allocated'
        ? selectedEvent.venue
        : (function () {
          const requested = [];
          const vi = selectedEvent.requisition?.annexureI_venue?.venueSelection || {};
          Object.entries(vi).forEach(([k, v]) => { if (v.selected) requested.push(k); });
          if (selectedEvent.requisition?.annexureII_audio?.venueName) requested.push(selectedEvent.requisition.annexureII_audio.venueName);
          return requested.length > 0 ? [...new Set(requested)].join(', ') : 'To be allocated';
        })(),
      professionalSociety: Array.isArray(step1?.professionalSocieties) && step1.professionalSocieties.length
        ? step1.professionalSocieties.join(', ')
        : '-',
      iicEvent: yesNo(step1?.isIIC),
    };
  }, [selectedEvent]);

  const getStatus = (item) => {
    // Auto-fetch logic
    const s1 = selectedEvent?.requisition?.step1;
    if (item.id === 'requisition-letter-hod' && selectedEvent?.id) return 'uploaded';
    if (item.id === 'event-brochure-flyer' && (selectedEvent?.posterDataUrl || selectedEvent?.posterUrl)) return 'uploaded';
    if (item.id === 'event-schedule' && s1?.schedule?.length > 0) return 'uploaded';
    if (item.id === 'geotagged-photos' && gallery.length > 0) return 'uploaded';
    if (item.id === 'feedback-participants' && selectedEvent?.studentFeedbackLink) return 'uploaded';
    if (item.id === 'feedback-resource-person' && selectedEvent?.resourcePersonFeedbackLink) return 'uploaded';
    if (item.id === 'event-report' && selectedEvent?.iqacSubmittedAt) return 'uploaded';

    if (verified[item.id]) return 'verified';
    if (item.autoGenerated) return 'autoGenerated';
    if (uploads[item.id]) return 'uploaded';
    return 'pending';
  };

  useEffect(() => {
    if (!hasStudentRoster) return;

    setRegistrationDetails((prev) => {
      const nextStudentsCount = studentsRegisteredFromRoster;
      const nextStudentsAttended = studentsAttendedFromRoster;

      if (
        Number(prev.studentsCount) === nextStudentsCount &&
        Number(prev.studentsAttended) === nextStudentsAttended
      ) {
        return prev;
      }

      return {
        ...prev,
        studentsCount: nextStudentsCount,
        studentsAttended: nextStudentsAttended,
      };
    });
  }, [hasStudentRoster, studentsRegisteredFromRoster, studentsAttendedFromRoster]);

  const totalRegistered =
    (Number(registrationDetails.studentsCount) || 0) +
    (Number(registrationDetails.facultyCount) || 0) +
    (Number(registrationDetails.externalCount) || 0);

  const totalAttended =
    (Number(registrationDetails.studentsAttended) || 0) +
    (Number(registrationDetails.facultyAttended) || 0) +
    (Number(registrationDetails.externalAttended) || 0);

  const noShowCount = Math.max(totalRegistered - totalAttended, 0);

  const onUpload = (itemId, e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // ── Size guard: reject immediately if > 250 KB ──
    if (file.size > MAX_DOC_SIZE) {
      setUploadErrors((prev) => ({
        ...prev,
        [itemId]: `File too large (${(file.size / 1024).toFixed(0)} KB). Maximum allowed is ${MAX_DOC_SIZE_LABEL}.`,
      }));
      e.target.value = '';
      return;
    }

    // Clear any previous error for this item
    setUploadErrors((prev) => { const next = { ...prev }; delete next[itemId]; return next; });

    const reader = new FileReader();
    reader.onload = (event) => {
      setUploads((prev) => ({
        ...prev,
        [itemId]: {
          fileName: file.name,
          fileType: file.type,
          fileSize: file.size,
          dataUrl: event.target?.result || '',
          uploadedAt: new Date().toISOString(),
        },
      }));
      setSubmitError('');
      setValidationError('');
      e.target.value = '';
    };
    reader.onerror = () => {
      setSubmitError('Unable to read uploaded file. Please try again.');
      e.target.value = '';
    };
    reader.readAsDataURL(file);
  };

  const handleFeedbackCsvUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const data = new Uint8Array(evt.target.result);
        const wb = XLSX.read(data, { type: 'array' });
        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];
        const jsonData = XLSX.utils.sheet_to_json(ws);

        if (jsonData.length === 0) {
          alert('The uploaded file appears to be empty.');
          return;
        }

        // Validate required headers
        const firstRow = jsonData[0];
        const headers = Object.keys(firstRow).map(h => h.toLowerCase());
        const required = ['name', 'roll_no', 'class', 'feedback'];
        const missing = required.filter(r => !headers.includes(r));

        if (missing.length > 0) {
          alert(`Error: Missing required columns: ${missing.join(', ')}.\n\nYour CSV must have these headers: name, roll_no, class, feedback`);
          return;
        }

        // Map data to the exact requested structure
        const mappedData = jsonData.map((row) => {
          // Find fields by case-insensitive matching
          const getVal = (field) => {
            const key = Object.keys(row).find(k => k.toLowerCase() === field);
            return row[key] || '';
          };

          return {
            student: getVal('name'),
            rollNo: getVal('roll_no'),
            class: getVal('class'),
            comment: getVal('feedback'),
            isManualUpload: true
          };
        });

        // 8. UI Behavior: Clear previous data when a new file is uploaded
        setAutoFeedbackSummary(prev => ({
          ...prev,
          comments: mappedData,
          totalResponses: mappedData.length,
          averageRating: 5
        }));

        /* Success alert removed per user request */
      } catch (err) {
        console.error('CSV Parsing failed:', err);
        setSubmitError('Failed to parse the file. Please ensure it is a valid CSV or Excel file.');
      }
    };
    reader.readAsArrayBuffer(file);
    e.target.value = '';
  };

  const handleGuestFeedbackCsvUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const data = new Uint8Array(evt.target.result);
        const wb = XLSX.read(data, { type: 'array' });
        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];
        const jsonData = XLSX.utils.sheet_to_json(ws);

        if (jsonData.length === 0) {
          alert('The uploaded file appears to be empty.');
          return;
        }

        // Validate required headers
        const firstRow = jsonData[0];
        const headers = Object.keys(firstRow).map(h => h.toLowerCase());
        const required = ['name', 'feedback'];
        const missing = required.filter(r => !headers.includes(r));

        if (missing.length > 0) {
          alert(`Error: Missing required columns: ${missing.join(', ')}.\n\nYour CSV must have at least: name, feedback`);
          return;
        }

        const getVal = (row, header) => {
          const key = Object.keys(row).find(k => k.toLowerCase() === header);
          return key ? row[key] : '';
        };

        const importedGuestFeedback = jsonData.map((row, idx) => ({
          id: Date.now() + idx,
          name: getVal(row, 'name'),
          designation: getVal(row, 'designation') || getVal(row, 'position') || '',
          organization: getVal(row, 'organization') || getVal(row, 'institution') || '',
          feedback: getVal(row, 'feedback') || getVal(row, 'comments') || '',
          highlights: getVal(row, 'highlights') || getVal(row, 'highlights_tags') || '',
        }));

        setGuestFeedback((prev) => [...prev, ...importedGuestFeedback]);
        /* Success alert removed per user request */

      } catch (err) {
        console.error('Error parsing Guest CSV:', err);
        alert('Failed to parse the file. Please ensure it follows the correct format.');
      } finally {
        e.target.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const toggleVerified = (item) => {
    const currentStatus = getStatus(item);
    if (currentStatus === 'pending') return;

    setVerified((prev) => ({
      ...prev,
      [item.id]: !prev[item.id],
    }));
  };

  const onGalleryUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setGallery((prev) => [...prev, {
        id: Date.now(),
        fileName: file.name,
        dataUrl: event.target.result,
        title: '',
        caption: '',
        dayTag: '', // For multi-day taglines
      }]);
    };
    reader.readAsDataURL(file);
    e.target.value = '';
  };

  const removeGalleryItem = (id) => {
    setGallery((prev) => prev.filter((item) => item.id !== id));
  };

  const addResourcePerson = () => {
    if (!resourcePersonForm.name.trim()) {
      alert('Please fill in the Resource Person Name');
      return;
    }
    setResourcePersons((prev) => [...prev, {
      id: Date.now(),
      ...resourcePersonForm,
    }]);
    setResourcePersonForm({
      name: '',
      designation: '',
      organization: '',
      topicsByDay: [],
      email: '',
      phone: '',
      expertise: '',
      bio: '',
      photo: null,
      rating: 5,
    });
  };

  const onResourcePersonPhoto = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      setResourcePersonForm(prev => ({
        ...prev,
        photo: {
          dataUrl: event.target.result,
          fileName: file.name
        }
      }));
    };
    reader.readAsDataURL(file);
    e.target.value = '';
  };

  const removeResourcePerson = (id) => {
    setResourcePersons((prev) => prev.filter((item) => item.id !== id));
  };

  const addGuestFeedback = () => {
    if (!feedbackForm.name.trim() || !feedbackForm.feedback.trim()) {
      alert('Please fill in Name and Feedback');
      return;
    }
    setGuestFeedback((prev) => [...prev, {
      id: Date.now(),
      ...feedbackForm,
    }]);
    setFeedbackForm({
      name: '',
      designation: '',
      organization: '',
      feedback: '',
      highlights: '',
    });
  };

  const removeGuestFeedback = (id) => {
    setGuestFeedback((prev) => prev.filter((item) => item.id !== id));
  };

  const updateStudentAttendanceStatus = (rowId, dayField, attendanceStatus) => {
    setStudentAttendanceRoster((prev) => prev.map((row) => (
      row.id === rowId
        ? { ...row, [dayField]: attendanceStatus }
        : row
    )));
  };

  const handleSubmit = async () => {
    const missing = CHECKLIST_ITEMS.filter((item) => {
      const isOptional = item.label.toLowerCase().includes('(optional)');
      return !item.autoGenerated && !isOptional && !uploads[item.id];
    });
    if (missing.length > 0) {
      setValidationError(`Please upload all required documents before submission. Missing: ${missing.length}.`);
      return;
    }

    // Guard: ensure no uploaded file exceeds the size limit
    const oversized = CHECKLIST_ITEMS.filter(
      (item) => !item.autoGenerated && uploads[item.id] && uploads[item.id].fileSize > MAX_DOC_SIZE
    );
    if (oversized.length > 0) {
      setValidationError(
        `${oversized.length} document(s) exceed the ${MAX_DOC_SIZE_LABEL} limit: ${oversized.map((i) => i.label).join(', ')}. Please re-upload smaller files.`
      );
      return;
    }

    const studentsCount = hasStudentRoster
      ? studentsRegisteredFromRoster
      : (Number(registrationDetails.studentsCount) || 0);
    const facultyCount = Number(registrationDetails.facultyCount) || 0;
    const externalCount = Number(registrationDetails.externalCount) || 0;
    const studentsAttended = hasStudentRoster
      ? studentsAttendedFromRoster
      : (Number(registrationDetails.studentsAttended) || 0);
    const facultyAttended = Number(registrationDetails.facultyAttended) || 0;
    const externalAttended = Number(registrationDetails.externalAttended) || 0;

    if (
      studentsAttended > studentsCount ||
      facultyAttended > facultyCount ||
      externalAttended > externalCount
    ) {
      setValidationError('Actual attendance cannot exceed registered count in any category.');
      return;
    }

    setValidationError('');
    setSubmitError('');
    setIsSubmitting(true);

    try {
      const checklist = CHECKLIST_ITEMS.map((item) => ({
        id: item.id,
        requirement: item.label,
        status: getStatus(item),
        autoGenerated: Boolean(item.autoGenerated),
        file: uploads[item.id] || null,
      }));

      const documents = Object.fromEntries(
        CHECKLIST_ITEMS.map((item) => {
          if (item.autoGenerated) {
            return [item.label, {
              autoGenerated: true,
              status: getStatus(item),
              source: item.id === 'attendance-sheet'
                ? 'Registration system'
                : item.id === 'feedback-participants'
                  ? 'Feedback module'
                  : 'Post Event Report module',
            }];
          }

          return [item.label, {
            ...(uploads[item.id] || {}),
            status: getStatus(item),
            verified: Boolean(verified[item.id]),
          }];
        })
      );

      const payload = {
        eventOutcome: eventOutcome,
        reportDetails,
        registrationDetails: {
          studentsCount,
          facultyCount,
          externalCount,
          studentsAttended,
          facultyAttended,
          externalAttended,
          studentAttendanceList: studentAttendanceRoster.map((row) => ({
            id: row.id,
            requestId: row.requestId || '',
            student: row.student || '',
            rollNo: row.rollNo || '',
            attendanceStatus: row.attendanceStatus,
            ...Object.fromEntries(Object.keys(row).filter(k => k.startsWith('day')).map(k => [k, row[k]]))
          })),
          periodStart: registrationDetails.periodStart,
          periodEnd: registrationDetails.periodEnd,
          mode: registrationDetails.mode,
        },
        resourcePersons: resourcePersons.map(({ id, ...item }) => item),
        gallery: gallery.map(({ id, ...item }) => item),
        guestFeedbackList: guestFeedback.map(({ id, ...item }) => item),
        documents,
        finalReport: documents['Event Report'] || null,
        checklist,
        iqacSubmissionCompletedAt: new Date().toISOString(),
      };

      const response = await fetch(`http://localhost:5001/api/iqac/${selectedEvent.id}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      if (!response.ok || !data.success) {
        throw new Error(data.message || 'Failed to submit IQAC documentation.');
      }

      navigate('/dashboard');
    } catch (error) {
      setSubmitError(error.message || 'Unable to submit IQAC documentation.');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!currentUser || !selectedEvent || !eventInfo) return null;

  return (
    <div className="min-h-screen bg-slate-50 pb-14">
      <Navbar />

      <main className="max-w-6xl mx-auto px-6 py-8 space-y-6">
        <div className="flex justify-end mb-6">
          <button onClick={() => navigate('/dashboard')} className="btn-secondary whitespace-nowrap">
            Back to Dashboard
          </button>
        </div>

        <header className="rounded-2xl border border-slate-200 bg-gradient-to-br from-white via-slate-50 to-blue-50/50 p-6 shadow-sm">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div>
              <h1 className="text-2xl font-bold text-slate-900">IQAC Submission Checklist</h1>
              <p className="mt-2 max-w-2xl text-sm text-slate-600">
                Final step of the event lifecycle. Upload, verify, and lock all documentation for a complete IQAC closure report.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm lg:min-w-[320px]">
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Completed</p>
                <p className="mt-1 font-bold text-slate-900">{progressStats.completedCount}/{CHECKLIST_ITEMS.length}</p>
              </div>
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Progress</p>
                <p className="mt-1 font-bold text-cse-accent">{progressStats.progressPercent}%</p>
              </div>
              <div className="col-span-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Event</p>
                <p className="mt-1 truncate font-semibold text-slate-900">{eventInfo.title}</p>
              </div>
            </div>
          </div>

          <div className="mt-5">
            <div className="mb-2 flex items-center justify-between text-sm font-semibold text-slate-700">
              <span>IQAC Documentation Progress</span>
              <span>{progressStats.completedCount} / {CHECKLIST_ITEMS.length} Documents Completed</span>
            </div>
            <div className="h-3 w-full overflow-hidden rounded-full bg-slate-100">
              <div
                className="h-full rounded-full bg-cse-accent transition-all"
                style={{ width: `${progressStats.progressPercent}%` }}
              />
            </div>
          </div>
        </header>

        {!eligibleForIQAC && (() => {
          const eventDate = selectedEvent?.date || selectedEvent?.requisition?.step1?.eventStartDate;
          const endTime = selectedEvent?.endTime || selectedEvent?.requisition?.step1?.eventEndTime;
          let windowExpired = false;
          if (eventDate && endTime) {
            const [h, m] = String(endTime).split(':').map(Number);
            const eventEnd = new Date(eventDate);
            eventEnd.setHours(h, m, 0, 0);
            const sevenDaysAfter = eventEnd.getTime() + (7 * 24 * 60 * 60 * 1000);
            windowExpired = Date.now() > eventEnd.getTime() && Date.now() > sevenDaysAfter;
          }
          return (
            <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5">
              <div className="flex items-start gap-3">
                <AlertCircle className="mt-0.5 text-amber-600" size={18} />
                <div>
                  <p className="text-sm font-bold text-amber-800">IQAC checklist is not available</p>
                  {windowExpired ? (
                    <p className="mt-1 text-sm text-amber-700">
                      The 7-day IQAC submission window has expired. Please contact your <strong>faculty coordinator</strong> to unlock an extension for this event.
                    </p>
                  ) : (
                    <p className="mt-1 text-sm text-amber-700">
                      IQAC submission is only available after the event has ended and must be completed within 7 days of the event end time.
                    </p>
                  )}
                </div>
              </div>
            </section>
          );
        })()}

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 1 - Event Information (Read-only)</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
            {[
              ['Event Title', eventInfo.title],
              ['Event Organizer Name', eventInfo.organizerName],
              ['Department', eventInfo.department],
              ['Event Type', eventInfo.eventType],
              ['Event Date (From - To)', eventInfo.eventDate],
              ['Event Venue', eventInfo.venue],
              ['Professional Society', eventInfo.professionalSociety],
              ['IIC Event', eventInfo.iicEvent],
            ].map(([label, value]) => (
              <div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
                <p className="mt-1 text-sm font-medium text-slate-900">{value || '-'}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Master Submission Checklist */}
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm overflow-hidden relative">
          <div className="absolute top-0 right-0 w-32 h-32 bg-slate-50 rounded-bl-full -z-10 opacity-50"></div>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
            <div>
              <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                <LayoutGrid size={22} className="text-cse-accent" /> Submission Progress Checklist
              </h2>
              <p className="text-sm text-slate-500 font-medium">Complete all sections to generate the final IQAC report</p>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <p className="text-2xl font-black text-slate-900 leading-none">{progressStats.progressPercent}%</p>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Total Completion</p>
              </div>
              <div className="w-16 h-16 rounded-full border-4 border-slate-100 flex items-center justify-center relative overflow-hidden">
                <div
                  className="absolute bottom-0 left-0 w-full bg-cse-accent transition-all duration-1000 ease-out"
                  style={{ height: `${progressStats.progressPercent}%` }}
                ></div>
                <span className="relative z-10 font-bold text-xs text-slate-900 mix-blend-difference">{progressStats.completedCount}/{progressStats.totalCount}</span>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {progressStats.sections.map((section) => (
              <div
                key={section.id}
                className={`flex items-center gap-3 p-3 rounded-xl border transition-all duration-300 ${section.isComplete
                  ? 'bg-emerald-50 border-emerald-100 shadow-sm'
                  : 'bg-white border-slate-100'
                  }`}
              >
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 transition-colors ${section.isComplete ? 'bg-emerald-500 text-white' : 'bg-slate-100 text-slate-400'
                  }`}>
                  {section.isComplete ? <Check size={18} strokeWidth={3} /> : <Circle size={14} />}
                </div>
                <p className={`text-xs font-bold leading-tight ${section.isComplete ? 'text-emerald-700' : 'text-slate-500'}`}>
                  {section.label}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-6 h-1.5 w-full bg-slate-100 rounded-full overflow-hidden flex gap-1 p-0.5">
            {progressStats.sections.map((s, i) => (
              <div
                key={s.id}
                className={`flex-1 rounded-full transition-all duration-700 ${s.isComplete ? 'bg-emerald-500' : 'bg-slate-200 opacity-30 shadow-inner'}`}
                style={{ transitionDelay: `${i * 100}ms` }}
              ></div>
            ))}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 2 - Registration Details</h2>
          <p className="mt-1 text-sm text-slate-600">Capture both registration and actual attendance to account for no-shows</p>

          {autoAttendanceStats && (
            <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">
              {[
                ['Registered', autoAttendanceStats.totalRegistered],
                ['Approved', autoAttendanceStats.approved],
                ['Rejected', autoAttendanceStats.rejected],
                ['Approval Rate (OD)', autoAttendanceStats.attendanceRate],
              ].map(([label, value]) => (
                <div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
                  <p className="mt-1 text-sm font-bold text-slate-900">{value ?? '-'}</p>
                </div>
              ))}
            </div>
          )}

          <p className="mt-3 text-xs text-slate-500">
            Note: OD stats above are registration workflow data. Enter actual attendees below for final IQAC reporting.
          </p>

          <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
            <div>
              <label className="block text-sm font-semibold text-slate-700">Students Registered</label>
              <input
                type="number"
                value={registrationDetails.studentsCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, studentsCount: e.target.value }))}
                disabled={isSubmitting || hasStudentRoster}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Faculty Registered</label>
              <input
                type="number"
                value={registrationDetails.facultyCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, facultyCount: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">External Registered</label>
              <input
                type="number"
                value={registrationDetails.externalCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, externalCount: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Students Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.studentsAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, studentsAttended: e.target.value }))}
                disabled={isSubmitting || hasStudentRoster}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Faculty Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.facultyAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, facultyAttended: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">External Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.externalAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, externalAttended: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Registration Mode</label>
              <select
                value={registrationDetails.mode}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, mode: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              >
                <option>In-person</option>
                <option>Online</option>
                <option>Hybrid</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700 font-sans">Actual Event Venue</label>
              <input
                type="text"
                value={registrationDetails.venue}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, venue: e.target.value }))}
                disabled={isSubmitting}
                placeholder="Terminal / Venue / Online Link"
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100 placeholder:text-slate-300"
              />
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Registered</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{totalRegistered}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Attended</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{totalAttended}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">No-Show Count</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{noShowCount}</p>
            </div>
          </div>

          {hasStudentRoster && (
            <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <h3 className="text-sm font-bold text-slate-900">Student Attendance Marking</h3>
                <p className="text-xs text-slate-600">
                  Attended: <span className="font-semibold text-emerald-700">{studentsAttendedFromRoster}</span> / {studentsRegisteredFromRoster}
                  {' '}| No-show: <span className="font-semibold text-amber-700">{studentsNoShowFromRoster}</span>
                  {' '}| Attendance: <span className="font-semibold text-cse-accent">{studentAttendancePercent}</span>
                </p>
              </div>

              <div className="mt-3 max-h-72 overflow-y-auto rounded-lg border border-slate-200 bg-white">
                <table className="min-w-full text-sm">
                  <thead className="sticky top-0 bg-slate-100">
                    <tr>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">#</th>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">Student</th>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">Roll No</th>
                      {(() => {
                        const cols = [];
                        for (let d = 1; d <= numberOfDays; d++) {
                          cols.push(<th key={d} className="px-3 py-2 text-left font-semibold text-slate-700">Day {d}</th>);
                        }
                        return cols;
                      })()}
                    </tr>
                  </thead>
                  <tbody>
                    {studentAttendanceRoster.map((row, idx) => (
                      <tr key={row.id || `${row.rollNo}-${idx + 1}`} className="border-t border-slate-100">
                        <td className="px-3 py-2 text-slate-700">{idx + 1}</td>
                        <td className="px-3 py-2 text-slate-800">{row.student || '-'}</td>
                        <td className="px-3 py-2 text-slate-600">{row.rollNo || '-'}</td>
                        {(() => {
                          const selects = [];
                          for (let d = 1; d <= numberOfDays; d++) {
                            selects.push(
                              <td key={d} className="px-3 py-2">
                                <select
                                  value={row[`day${d}`]}
                                  onChange={(e) => updateStudentAttendanceStatus(row.id, `day${d}`, e.target.value)}
                                  disabled={isSubmitting}
                                  className="w-full rounded-lg border border-slate-300 px-2 py-1.5 text-[10px] font-bold text-slate-700"
                                >
                                  <option value="ATTENDED">P</option>
                                  <option value="FN">FN</option>
                                  <option value="AN">AN</option>
                                  <option value="NOT_ATTENDED">A</option>
                                </select>
                              </td>
                            );
                          }
                          return selects;
                        })()}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-4">
            <div>
              <h2 className="text-lg font-bold text-slate-900">Section 3 - Student Feedback</h2>
              <p className="text-sm text-slate-600">Collected automatically or uploaded from external sources (Google Forms)</p>
            </div>
            <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-purple-200 bg-purple-50 px-4 py-2 text-sm font-semibold text-purple-700 hover:bg-purple-100 transition-colors">
              <Upload size={16} /> Upload Feedback CSV
              <input
                type="file"
                accept=".csv,.xlsx,.xls"
                className="hidden"
                onChange={handleFeedbackCsvUpload}
                disabled={isSubmitting}
              />
            </label>
          </div>

          <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4 mb-4">
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Responses</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{autoFeedbackSummary?.totalResponses ?? 0}</p>
            </div>
          </div>

          {autoFeedbackSummary?.comments?.length > 0 ? (
            <div className="max-h-80 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-md custom-scrollbar">
              <table className="min-w-full text-sm divide-y divide-slate-200">
                <thead className="bg-[#f8fafc] sticky top-0 z-10">
                  <tr>
                    <th className="px-5 py-4 text-left font-bold text-slate-800 uppercase tracking-wider w-16 bg-slate-100/50">S.No</th>
                    <th className="px-5 py-4 text-left font-bold text-slate-800 uppercase tracking-wider w-1/4">Name</th>
                    <th className="px-5 py-4 text-left font-bold text-slate-800 uppercase tracking-wider w-1/4 text-center">Roll No</th>
                    <th className="px-5 py-4 text-left font-bold text-slate-800 uppercase tracking-wider w-1/6 text-center">Class</th>
                    <th className="px-5 py-4 text-left font-bold text-slate-800 uppercase tracking-wider font-sans">Feedback</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 bg-white">
                  {autoFeedbackSummary.comments.map((item, idx) => (
                    <tr key={`${item.rollNo}-${idx}`} className="hover:bg-blue-50/30 transition-all group border-b border-transparent last:border-0">
                      <td className="px-5 py-4 text-slate-400 font-bold tabular-nums group-hover:text-blue-500">{idx + 1}</td>
                      <td className="px-5 py-4 text-slate-900 font-extrabold tracking-tight">{item.student}</td>
                      <td className="px-5 py-4 text-slate-600 font-mono text-center bg-slate-50/40 group-hover:bg-transparent">{item.rollNo}</td>
                      <td className="px-5 py-4 text-slate-500 font-medium text-center italic">{item.class || '-'}</td>
                      <td className="px-5 py-4 text-slate-700 leading-relaxed font-outfit">
                        {item.comment ? (
                          <div className="flex items-start gap-2">
                            <span className="text-slate-300">"</span>
                            <span>{item.comment}</span>
                            <span className="text-slate-300">"</span>
                          </div>
                        ) : (
                          <span className="text-slate-300 font-normal italic">No feedback provided</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="p-12 text-center rounded-xl border border-dashed border-slate-300 bg-slate-50/50">
              <FileText size={40} className="mx-auto text-slate-300 mb-3" />
              <p className="text-sm text-slate-500">No student feedback submitted yet.</p>
              <p className="text-xs text-slate-400 mt-1">Submit feedback via portal or upload a CSV file.</p>
            </div>
          )}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 4 - Event Gallery</h2>
          <p className="mt-1 text-sm text-slate-600">Upload photos and images from the event. For multi-day events, please upload photos for each day and mention the Day tagline (e.g. Day 1, Day 2).</p>

          <div className="mt-4 p-4 border rounded-xl bg-slate-50 flex items-center gap-4">
            <div className="w-24 h-24 rounded-lg overflow-hidden border border-slate-200">
              <img src={selectedEvent.posterDataUrl || selectedEvent.posterUrl || defaultPoster} className="w-full h-full object-cover" alt="poster" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-700 uppercase tracking-tight">Official Event Poster</p>
              <p className="text-xs text-slate-500">Fetched from event creation details</p>
            </div>
          </div>

          <div className="mt-6 space-y-4">
            <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-cse-accent/30 bg-cse-accent/5 px-4 py-2.5 text-sm font-semibold text-cse-accent hover:bg-cse-accent/10 disabled:opacity-60">
              <Upload size={16} /> Add Photo
              <input
                type="file"
                accept=".jpg,.jpeg,.png,.gif"
                className="hidden"
                onChange={onGalleryUpload}
                disabled={isSubmitting}
              />
            </label>

            {gallery.length > 0 && (
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                {gallery.map((item) => (
                  <div key={item.id} className="rounded-lg border border-slate-200 p-3">
                    <img
                      src={item.dataUrl}
                      alt="gallery"
                      className="w-full h-32 object-cover rounded-lg mb-2"
                    />
                    <div className="space-y-2">
                      <input
                        type="text"
                        placeholder="Tagline (e.g. Day 1 Session 1)"
                        value={item.dayTag || ''}
                        onChange={(e) => setGallery((prev) =>
                          prev.map((g) => g.id === item.id ? { ...g, dayTag: e.target.value } : g)
                        )}
                        className="w-full text-xs rounded border border-slate-300 px-2 py-1"
                      />
                      <input
                        type="text"
                        placeholder="Caption (optional)"
                        value={item.title}
                        onChange={(e) => setGallery((prev) =>
                          prev.map((g) => g.id === item.id ? { ...g, title: e.target.value } : g)
                        )}
                        className="w-full text-xs rounded border border-slate-300 px-2 py-1 invisible h-0"
                      />
                      <button
                        type="button"
                        onClick={() => removeGalleryItem(item.id)}
                        className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                      >
                        <X size={14} /> Remove
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {gallery.length === 0 && (
              <p className="text-sm text-slate-500">No photos uploaded yet.</p>
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 5 - Detailed Event Report Content</h2>
          <p className="mt-1 text-sm text-slate-600">This content is used to generate the academic event report. Pre-filled with defaults based on event theme.</p>

          <div className="mt-6 space-y-6">
            <div>
              <label className="text-sm font-bold text-slate-700">Event Final Outcome *</label>
              <textarea
                value={eventOutcome}
                onChange={(e) => setEventOutcome(e.target.value)}
                rows={2}
                placeholder="Brief summary of the completion status..."
                className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:ring-cse-accent/30 focus:border-cse-accent"
              />
            </div>

            <div>
              <label className="text-sm font-bold text-slate-700">Description of the Event *</label>
              <textarea
                value={reportDetails.description}
                onChange={(e) => setReportDetails(p => ({ ...p, description: e.target.value }))}
                rows={5}
                placeholder="Detailed narrative of how the event was conducted..."
                className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:ring-cse-accent/30 focus:border-cse-accent"
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-sm font-bold text-slate-700 mb-2 block">Event Objectives (One per line)</label>
                <textarea
                  value={reportDetails.objectives.join('\n')}
                  onChange={(e) => setReportDetails(p => ({ ...p, objectives: e.target.value.split('\n').filter(Boolean) }))}
                  rows={6}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-mono"
                />
              </div>
              <div>
                <label className="text-sm font-bold text-slate-700 mb-2 block">Event Outcomes (One per line)</label>
                <textarea
                  value={reportDetails.outcomes.join('\n')}
                  onChange={(e) => setReportDetails(p => ({ ...p, outcomes: e.target.value.split('\n').filter(Boolean) }))}
                  rows={6}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-mono"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-bold text-slate-700">Technical Skills Gained</label>
                <input
                  type="text"
                  value={reportDetails.benefits.technical || ''}
                  onChange={(e) => setReportDetails(p => ({ ...p, benefits: { ...p.benefits, technical: e.target.value } }))}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                />
              </div>
              <div>
                <label className="text-sm font-bold text-slate-700">Industry Benefits</label>
                <input
                  type="text"
                  value={reportDetails.benefits.industry || ''}
                  onChange={(e) => setReportDetails(p => ({ ...p, benefits: { ...p.benefits, industry: e.target.value } }))}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
              <div>
                <label className="text-sm font-bold text-slate-700">Website Coverage Link</label>
                <input
                  type="text"
                  value={reportDetails.socialMedia.website || ''}
                  onChange={(e) => setReportDetails(p => ({ ...p, socialMedia: { ...p.socialMedia, website: e.target.value } }))}
                  placeholder="https://collegewebsite.edu/blog/..."
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs"
                />
              </div>
              <div>
                <label className="text-sm font-bold text-slate-700">Social Media URL</label>
                <input
                  type="text"
                  value={reportDetails.socialMedia.social || ''}
                  onChange={(e) => setReportDetails(p => ({ ...p, socialMedia: { ...p.socialMedia, social: e.target.value } }))}
                  placeholder="Instagram/LinkedIn post link..."
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs"
                />
              </div>
            </div>
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between gap-4 mb-2">
            <div>
              <h2 className="text-lg font-bold text-slate-900">Section 5 - Guest Feedback (Via CSV)</h2>
              <p className="text-sm text-slate-600">Import guest feedback collected via Google Forms or WhatsApp</p>
            </div>
            <div className="relative">
              <input
                type="file"
                accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                onChange={handleGuestFeedbackCsvUpload}
                disabled={isSubmitting}
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer disabled:cursor-not-allowed"
              />
              <div className="flex items-center gap-2 px-5 py-2.5 bg-cse-accent text-white rounded-xl text-sm font-bold hover:bg-cse-accent/90 transition-all shadow-md shadow-blue-900/10">
                <FileUp size={18} /> Upload Guest Feedback CSV
              </div>
            </div>
          </div>

          <div className="mt-8">
            {guestFeedback.length > 0 ? (
              <div className="overflow-hidden border border-slate-200 rounded-xl bg-white">
                <table className="min-w-full divide-y divide-slate-200">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="w-12 px-4 py-3 text-left text-[10px] font-bold text-slate-500 uppercase tracking-widest text-center">S.No</th>
                      <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 uppercase tracking-widest">Guest Info</th>
                      <th className="px-4 py-3 text-left text-[10px] font-bold text-slate-500 uppercase tracking-widest">Feedback Comments</th>
                      <th className="px-4 py-3 text-right text-[10px] font-bold text-slate-500 uppercase tracking-widest">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 bg-white">
                    {guestFeedback.map((feedback, index) => (
                      <tr key={feedback.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-4 text-center text-xs font-bold text-slate-400">{index + 1}</td>
                        <td className="px-4 py-4 whitespace-nowrap">
                          <div className="font-bold text-slate-900 text-sm">{feedback.name}</div>
                          <div className="text-[10px] text-slate-500 font-bold uppercase truncate max-w-[150px]">{feedback.designation || 'Guest'}</div>
                          <div className="text-[9px] text-slate-400 truncate max-w-[150px]">{feedback.organization}</div>
                        </td>
                        <td className="px-4 py-4">
                          <p className="text-xs text-slate-700 leading-relaxed italic line-clamp-2">"{feedback.feedback}"</p>
                          {feedback.highlights && (
                            <div className="flex flex-wrap gap-1 mt-1.5">
                              {feedback.highlights.split(',').map((h, i) => (
                                <span key={i} className="text-[9px] bg-indigo-50 text-indigo-600 px-2 py-0.5 rounded-full font-bold border border-indigo-100">{h.trim()}</span>
                              ))}
                            </div>
                          )}
                        </td>
                        <td className="px-4 py-4 text-right">
                          <button
                            type="button"
                            onClick={() => removeGuestFeedback(feedback.id)}
                            className="p-1.5 text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                          >
                            <X size={16} />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center p-12 border-2 border-dashed border-slate-200 rounded-2xl bg-slate-50/50">
                <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center shadow-sm text-slate-300 mb-4">
                  <FileText size={32} />
                </div>
                <p className="text-slate-500 font-medium">No Guest Feedback Uploaded</p>
                <p className="text-xs text-slate-400 mt-1 uppercase tracking-tighter">Columns Required: Name, Feedback</p>
              </div>
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-indigo-50 text-indigo-600 rounded-xl flex items-center justify-center">
              <Globe size={20} />
            </div>
            <div>
              <h2 className="text-lg font-black text-slate-900 leading-tight uppercase tracking-tight">Academic Alignment</h2>
              <p className="text-xs text-slate-500 font-bold uppercase tracking-widest mt-0.5">Section 6 • Strategic Mapping (SDG & POs)</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1.5 block">Primary SDG Goal</label>
              <select
                value={reportDetails.mapping?.sdg || '4'}
                onChange={(e) => setReportDetails(p => ({ ...p, mapping: { ...p.mapping, sdg: e.target.value } }))}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold focus:ring-cse-accent/30 focus:border-cse-accent cursor-pointer"
              >
                {Object.entries(SDG_NAMES).map(([id, name]) => (
                  <option key={id} value={id}>SDG {id}: {name}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1.5 block">Programme Outcomes (POs)</label>
              <input
                type="text"
                placeholder="e.g. 1, 3, 5, 8, 12"
                value={reportDetails.mapping?.po || ''}
                onChange={(e) => setReportDetails(p => ({ ...p, mapping: { ...p.mapping, po: e.target.value } }))}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold focus:ring-cse-accent/30 focus:border-cse-accent font-mono"
              />
            </div>
            <div>
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1.5 block">PSOs Mapping</label>
              <input
                type="text"
                placeholder="e.g. 1, 2"
                value={reportDetails.mapping?.pso || ''}
                onChange={(e) => setReportDetails(p => ({ ...p, mapping: { ...p.mapping, pso: e.target.value } }))}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold focus:ring-cse-accent/30 focus:border-cse-accent font-mono"
              />
            </div>
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 6 - Resource Persons / Speakers</h2>
          <p className="mt-1 text-sm text-slate-600">Add details of all resource persons and speakers who participated in the event</p>

          <div className="mt-4 space-y-4">
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-3">
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Name *</label>
                  <input
                    type="text"
                    placeholder="Full name"
                    value={resourcePersonForm.name}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, name: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Designation</label>
                  <input
                    type="text"
                    placeholder="e.g., Professor, Industry Expert"
                    value={resourcePersonForm.designation}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, designation: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Email Address</label>
                  <input
                    type="email"
                    placeholder="email@example.com"
                    value={resourcePersonForm.email}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, email: e.target.value }))}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Phone Number</label>
                  <input
                    type="text"
                    placeholder="+91 9876543210"
                    value={resourcePersonForm.phone}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, phone: e.target.value }))}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                  />
                </div>
              </div>

              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Areas of Expertise (e.g. AI, Cloud)</label>
                <input
                  type="text"
                  placeholder="Expertise keywords"
                  value={resourcePersonForm.expertise}
                  onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, expertise: e.target.value }))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                />
              </div>

              <div className="flex gap-4 items-start">
                <div className="flex-1">
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Brief Bio / Credentials</label>
                  <textarea
                    placeholder="A few lines about the speaker's background..."
                    value={resourcePersonForm.bio}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, bio: e.target.value }))}
                    rows={3}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                  />
                </div>
                <div className="w-32">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-tight mb-2 block">Photo</label>
                  <div className="relative group">
                    <div className="w-32 h-32 rounded-xl border-2 border-dashed border-slate-300 bg-white flex items-center justify-center overflow-hidden transition-all group-hover:border-cse-accent">
                      {resourcePersonForm.photo ? (
                        <img src={resourcePersonForm.photo.dataUrl} className="w-full h-full object-cover" alt="speaker" />
                      ) : (
                        <div className="text-slate-300 flex flex-col items-center gap-1">
                          <Camera size={24} />
                          <span className="text-[10px]">Upload</span>
                        </div>
                      )}
                      <input
                        type="file"
                        accept="image/*"
                        onChange={onResourcePersonPhoto}
                        className="absolute inset-0 opacity-0 cursor-pointer"
                      />
                    </div>
                    {resourcePersonForm.photo && (
                      <button
                        onClick={() => setResourcePersonForm(p => ({ ...p, photo: null }))}
                        className="absolute -top-2 -right-2 bg-red-500 text-white p-1 rounded-full shadow-lg"
                      >
                        <X size={12} />
                      </button>
                    )}
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700 uppercase tracking-tighter text-[10px]">Organization / Institution</label>
                  <input
                    type="text"
                    placeholder="Organization name"
                    value={resourcePersonForm.organization}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, organization: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100 placeholder:text-slate-400"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700 uppercase tracking-tighter text-[10px]">Topic / Session Handled</label>
                  {(() => {
                    const topics = [];
                    for (let i = 1; i <= numberOfDays; i++) {
                      topics.push(
                        <input
                          key={i}
                          type="text"
                          placeholder={`Day ${i} topic covered`}
                          value={resourcePersonForm.topicsByDay?.[i - 1] || ''}
                          onChange={(e) => {
                            const newTopics = [...(resourcePersonForm.topicsByDay || [])];
                            newTopics[i - 1] = e.target.value;
                            setResourcePersonForm(prev => ({ ...prev, topicsByDay: newTopics }));
                          }}
                          className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-xs mb-1"
                        />
                      );
                    }
                    return topics;
                  })()}
                </div>
              </div>

              <button
                type="button"
                onClick={addResourcePerson}
                disabled={isSubmitting}
                className="inline-flex items-center gap-2 rounded-lg bg-cse-accent px-4 py-2 text-sm font-semibold text-white hover:bg-cse-accent/90 disabled:opacity-60"
              >
                <Plus size={16} /> Add Resource Person
              </button>
            </div>

            {resourcePersons.length > 0 && (
              <div className="space-y-2">
                <p className="text-sm font-semibold text-slate-700">Added Resource Persons ({resourcePersons.length})</p>
                {resourcePersons.map((person) => (
                  <div key={person.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-semibold text-slate-900">{person.name}</p>
                        {person.designation && <p className="text-xs text-slate-600">{person.designation}</p>}
                        {person.organization && <p className="text-xs text-slate-600">{person.organization}</p>}
                        {(person.topicsByDay || []).map((t, idx) => t ? (
                          <p key={idx} className="text-xs text-slate-500 mt-0.5">Day {idx + 1}: {t}</p>
                        ) : null)}
                      </div>
                      <button
                        type="button"
                        onClick={() => removeResourcePerson(person.id)}
                        className="text-red-600 hover:text-red-700"
                      >
                        <X size={18} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {resourcePersons.length === 0 && (
              <p className="text-sm text-slate-500">No resource persons added yet.</p>
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h2 className="text-lg font-bold text-slate-900">Section 7 - IQAC Documentation Checklist</h2>
            <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600">
              {CHECKLIST_ITEMS.length} Required Items
            </span>
          </div>

          {/* ── 250 KB upfront notice ── */}
          <div className="mt-3 flex items-start gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3">
            <AlertCircle size={15} className="mt-0.5 shrink-0 text-blue-600" />
            <p className="text-xs text-blue-800">
              <span className="font-bold">Document size limit: {MAX_DOC_SIZE_LABEL} per file.</span>{' '}
              Please compress or reduce your documents before uploading. Files exceeding {MAX_DOC_SIZE_LABEL} will be rejected automatically.
              Accepted formats: PDF, DOC, DOCX, JPG, PNG.
            </p>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 lg:grid-cols-2">
            {CHECKLIST_ITEMS.map((item, index) => {
              const status = getStatus(item);
              const file = uploads[item.id];
              const canVerify = status === 'uploaded' || status === 'autoGenerated' || status === 'verified';

              return (
                <article
                  key={item.id}
                  className={`rounded-xl border p-4 ${uploadErrors[item.id]
                    ? 'border-red-300 bg-red-50/60'
                    : 'border-slate-200 bg-slate-50/50'
                    }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Requirement {index + 1}</p>
                      <h3 className="mt-1 text-sm font-semibold text-slate-900">{item.label}</h3>
                    </div>
                    <StatusBadge status={status} />
                  </div>

                  <div className="mt-3 space-y-2">
                    {item.autoGenerated ? (
                      <span className="inline-flex items-center rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700">
                        {['requisition-letter-hod', 'event-brochure-flyer', 'event-schedule', 'geotagged-photos'].includes(item.id) ? 'System Provided' : 'Auto from system'}
                      </span>
                    ) : (
                      <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-cse-accent/30 bg-cse-accent/5 px-3 py-1.5 text-xs font-semibold text-cse-accent hover:bg-cse-accent/10">
                        <Upload size={14} /> Upload Document
                        <input
                          type="file"
                          accept={ACCEPTED_TYPES}
                          className="hidden"
                          onChange={(e) => onUpload(item.id, e)}
                          disabled={!eligibleForIQAC || isSubmitting}
                        />
                      </label>
                    )}

                    {/* Per-item upload error (size exceeded) */}
                    {uploadErrors[item.id] && (
                      <p className="flex items-center gap-1.5 text-xs font-semibold text-red-600">
                        <AlertCircle size={13} />
                        {uploadErrors[item.id]}
                      </p>
                    )}

                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-xs text-slate-500">
                        {item.id === 'feedback-participants' && selectedEvent?.studentFeedbackLink
                          ? `Google Form: ${selectedEvent.studentFeedbackLink}`
                          : item.id === 'feedback-resource-person' && selectedEvent?.resourcePersonFeedbackLink
                            ? `Google Form: ${selectedEvent.resourcePersonFeedbackLink}`
                            : file
                              ? `File: ${file.fileName}`
                              : item.autoGenerated
                                ? 'Generated from workflow data'
                                : `Max ${MAX_DOC_SIZE_LABEL} · PDF, DOC, DOCX, JPG, PNG`}
                      </p>
                      {/* File size pill */}
                      {file && (
                        <span
                          className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold ${file.fileSize > MAX_DOC_SIZE
                            ? 'bg-red-100 text-red-700'
                            : 'bg-emerald-100 text-emerald-700'
                            }`}
                        >
                          {(file.fileSize / 1024).toFixed(1)} KB
                        </span>
                      )}
                      {(item.id === 'feedback-participants' && selectedEvent?.studentFeedbackLink) && (
                        <a
                          href={selectedEvent.studentFeedbackLink}
                          target="_blank"
                          rel="noreferrer"
                          className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 hover:bg-blue-100"
                        >
                          Open Link
                        </a>
                      )}
                      {(item.id === 'feedback-resource-person' && selectedEvent?.resourcePersonFeedbackLink) && (
                        <a
                          href={selectedEvent.resourcePersonFeedbackLink}
                          target="_blank"
                          rel="noreferrer"
                          className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 hover:bg-blue-100"
                        >
                          Open Link
                        </a>
                      )}
                      {item.id === 'event-report' && (
                        <button
                          onClick={() => setShowReportModal(true)}
                          className="inline-flex items-center gap-1.5 rounded-lg border border-purple-200 bg-purple-50 px-2.5 py-1 text-xs font-bold text-purple-700 hover:bg-purple-100 transition-all shadow-sm"
                        >
                          <FileText size={12} /> View/Generate Report
                        </button>
                      )}
                      {file && file.dataUrl && (
                        <a
                          href={file.dataUrl}
                          download={file.fileName}
                          className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 hover:bg-blue-100"
                        >
                          Download
                        </a>
                      )}
                    </div>

                    {canVerify && (
                      <button
                        type="button"
                        onClick={() => toggleVerified(item)}
                        disabled={!eligibleForIQAC || isSubmitting}
                        className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 disabled:opacity-60"
                      >
                        <CheckCircle2 size={12} />
                        {status === 'verified' ? 'Unverify' : 'Mark Verified'}
                      </button>
                    )}
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        {(validationError || submitError) && (
          <section className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {validationError || submitError}
          </section>
        )}

        <footer className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs text-slate-500">
            Final submission validates all required documents and closes the event as IQAC Submission Completed.
          </p>
          <button
            type="button"
            onClick={handleSubmit}
            disabled={isSubmitting || !eligibleForIQAC || Boolean(selectedEvent.iqacSubmittedAt)}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-cse-accent px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400"
          >
            {isSubmitting ? <Loader2 size={16} className="animate-spin" /> : <FileCheck2 size={16} />}
            {selectedEvent.iqacSubmittedAt ? 'IQAC Already Submitted' : 'Submit IQAC Documentation'}
          </button>
        </footer>
        {/* Event Report Modal */}
        {showReportModal && (
          <EventReportModal
            event={selectedEvent}
            resourcePersons={resourcePersons}
            registrationDetails={registrationDetails}
            reportDetails={reportDetails}
            feedbackStats={autoFeedbackSummary}
            guestFeedback={guestFeedback}
            gallery={gallery}
            onClose={() => setShowReportModal(false)}
          />
        )}
      </main>
    </div>
  );
};

export default IQACSubmission;
