import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertCircle, CheckCircle2, FileCheck2, Loader2, Upload, X, Plus, Star } from 'lucide-react';
import Navbar from '../components/Navbar';
import { useAppContext } from '../context/AppContext';
import { EventStatus } from '../types';

const CHECKLIST_ITEMS = [
  { id: 'requisition-letter-hod', label: 'Requisition Letter to HoD' },
  { id: 'food-transport-requisition', label: 'Food / Transport Requisition Letter' },
  { id: 'financial-assistance-letter', label: 'Financial Assistance Letter' },
  { id: 'letter-to-resource-person', label: 'Letter to Resource Person' },
  { id: 'acceptance-mail-resource-person', label: 'Acceptance Mail from Resource Person' },
  { id: 'event-brochure-flyer', label: 'Event Brochure / Flyer' },
  { id: 'event-schedule', label: 'Event Schedule' },
  { id: 'invitation-copy', label: 'Invitation Copy' },
  { id: 'cv-resource-person', label: 'CV of Resource Person' },
  { id: 'attendance-sheet', label: 'Attendance Sheet', autoGenerated: true },
  { id: 'feedback-resource-person', label: 'Feedback from Resource Person' },
  { id: 'feedback-participants', label: 'Feedback from Participants', autoGenerated: true },
  { id: 'event-report', label: 'Event Report', autoGenerated: true },
  { id: 'geotagged-photos', label: 'Geotagged Photos' },
  { id: 'certificates-issued', label: 'Certificates Issued' },
  { id: 'account-settlement-bills', label: 'Account Settlement / Bills' },
  { id: 'press-media-materials', label: 'Press / Media Materials' },
];

const ACCEPTED_TYPES = '.pdf,.doc,.docx,.jpg,.jpeg,.png';
const MAX_DOC_SIZE = 250 * 1024; // 250 KB in bytes
const MAX_DOC_SIZE_LABEL = '250 KB';

const STATUS_THEME = {
  pending: 'bg-red-50 text-red-700 border border-red-200',
  uploaded: 'bg-blue-50 text-blue-700 border border-blue-200',
  autoGenerated: 'bg-slate-100 text-slate-700 border border-slate-200',
  verified: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
};

const toDateRange = (event) => {
  const start = event?.requisition?.step1?.eventStartDate || event?.date || '-';
  const end = event?.requisition?.step1?.eventEndDate || event?.date || '-';
  return `${start} - ${end}`;
};

const yesNo = (value) => (String(value || '').toLowerCase() === 'yes' ? 'Yes' : 'No');

const isEventEndTimePassed = (event) => {
  if (!event) return false;
  const eventDate = event.date || event.requisition?.step1?.eventStartDate;
  const endTime = event.endTime || event.requisition?.step1?.eventEndTime;
  if (!eventDate || !endTime) return false;
  
  const [hours, minutes] = String(endTime).split(':').map(Number);
  const eventEnd = new Date(eventDate);
  eventEnd.setHours(hours, minutes, 0, 0);
  
  const now = Date.now();
  const endMs = eventEnd.getTime();
  const sevenDaysAfter = endMs + (7 * 24 * 60 * 60 * 1000); 
  
  // Must be after event end AND within 7 days
  return now > endMs && now <= sevenDaysAfter;
};

const StatusBadge = ({ status }) => {
  const labelMap = {
    pending: 'Pending',
    uploaded: 'Uploaded',
    autoGenerated: 'Auto Generated',
    verified: 'Verified',
  };

  return (
    <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${STATUS_THEME[status]}`}>
      {labelMap[status]}
    </span>
  );
};

const IQACSubmission = () => {
  const { currentUser, selectedEvent } = useAppContext();
  const navigate = useNavigate();

  const [uploads, setUploads] = useState({});
  const [uploadErrors, setUploadErrors] = useState({});
  const [verified, setVerified] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [validationError, setValidationError] = useState('');
  
  // New state for gallery, guest feedback, and registration details
  const [gallery, setGallery] = useState([]);
  const [guestFeedback, setGuestFeedback] = useState([]);
  const [registrationDetails, setRegistrationDetails] = useState({
    studentsCount: 0,
    facultyCount: 0,
    externalCount: 0,
    studentsAttended: 0,
    facultyAttended: 0,
    externalAttended: 0,
    periodStart: '',
    periodEnd: '',
    mode: 'Hybrid',
  });
  const [isFetchingStats, setIsFetchingStats] = useState(false);
  const [autoAttendanceStats, setAutoAttendanceStats] = useState(null);
  const [autoFeedbackSummary, setAutoFeedbackSummary] = useState(null);
  const [studentAttendanceRoster, setStudentAttendanceRoster] = useState([]);

  // Resource persons state
  const [resourcePersons, setResourcePersons] = useState([]);
  const [resourcePersonForm, setResourcePersonForm] = useState({
    name: '',
    designation: '',
    organization: '',
    topic: '',
    rating: 5,
  });

  // New feedback form state
  const [feedbackForm, setFeedbackForm] = useState({
    name: '',
    designation: '',
    organization: '',
    rating: 5,
    feedback: '',
  });

  useEffect(() => {
    if (!currentUser) {
      navigate('/');
      return;
    }
    if (!selectedEvent) {
      navigate('/dashboard');
      return;
    }
    
    // Fetch OD request stats to auto-populate registration details
    const fetchODStats = async () => {
      try {
        setIsFetchingStats(true);
        const response = await fetch(`http://localhost:5001/api/iqac/${selectedEvent.id}`);
        const data = await response.json();

        if (data.success) {
          const { attendanceStats = null, feedbackSummary = null, iqacData = null } = data;
          const savedStudentAttendance = iqacData?.registration?.attendance?.studentAttendanceList || [];

          setAutoAttendanceStats(attendanceStats);
          setAutoFeedbackSummary(feedbackSummary);

          // Populate saved data if exists
          if (iqacData) {
            if (iqacData.gallery) setGallery(iqacData.gallery.map((g, i) => ({ ...g, id: g.id || `saved-g-${i}` })));
            if (iqacData.resourcePersons) setResourcePersons(iqacData.resourcePersons.map((rp, i) => ({ ...rp, id: rp.id || `saved-rp-${i}` })));
            if (iqacData.guestFeedback) setGuestFeedback(iqacData.guestFeedback.map((gf, i) => ({ ...gf, id: gf.id || `saved-gf-${i}` })));
            
            if (iqacData.registration) {
              setRegistrationDetails({
                studentsCount: iqacData.registration.categories?.students || 0,
                facultyCount: iqacData.registration.categories?.faculty || 0,
                externalCount: iqacData.registration.categories?.external || 0,
                studentsAttended: iqacData.registration.attendance?.categories?.students || 0,
                facultyAttended: iqacData.registration.attendance?.categories?.faculty || 0,
                externalAttended: iqacData.registration.attendance?.categories?.external || 0,
                periodStart: iqacData.registration.period?.start || '',
                periodEnd: iqacData.registration.period?.end || '',
                mode: iqacData.registration.mode || 'Hybrid',
              });
            }

            if (iqacData.documents) {
              const nextUploads = {};
              const nextVerified = {};
              Object.entries(iqacData.documents).forEach(([label, doc]) => {
                const item = CHECKLIST_ITEMS.find(i => i.label === label);
                if (item) {
                  if (!doc.autoGenerated) nextUploads[item.id] = doc;
                  if (doc.verified) nextVerified[item.id] = true;
                }
              });
              setUploads(nextUploads);
              setVerified(nextVerified);
            }
          }

          if (attendanceStats) {
            const rows = Array.isArray(attendanceStats.rows) ? attendanceStats.rows : [];
            let nextRoster = [];

            if (Array.isArray(savedStudentAttendance) && savedStudentAttendance.length > 0) {
              nextRoster = savedStudentAttendance.map((item, idx) => ({
                id: item.id || item.requestId || item.rollNo || `saved-${idx + 1}`,
                requestId: item.requestId || item.id || '',
                student: item.student || item.studentName || '',
                rollNo: item.rollNo || '',
                attendanceStatus: String(item.attendanceStatus || item.status || 'ATTENDED').toUpperCase() === 'NOT_ATTENDED'
                  ? 'NOT_ATTENDED'
                  : 'ATTENDED',
              }));
            } else {
              nextRoster = rows.map((row, idx) => ({
                id: row.id || row.requestId || row.rollNo || `row-${idx + 1}`,
                requestId: row.id || row.requestId || '',
                student: row.student || '',
                rollNo: row.rollNo || '',
                attendanceStatus: 'ATTENDED',
              }));
            }

            setStudentAttendanceRoster(nextRoster);

            if (!iqacData) {
              const studentsRegisteredFromRoster = nextRoster.length;
              const studentsAttendedFromRoster = nextRoster.filter((item) => item.attendanceStatus === 'ATTENDED').length;

              setRegistrationDetails((prev) => ({
                ...prev,
                studentsCount: studentsRegisteredFromRoster || attendanceStats.totalRegistered || 0,
                studentsAttended: studentsAttendedFromRoster || attendanceStats.totalRegistered || 0,
                periodStart: selectedEvent.date || '',
                periodEnd: selectedEvent.date || '',
              }));
            }
          }
        }
      } catch (error) {
        console.error('Failed to fetch OD stats:', error);
      } finally {
        setIsFetchingStats(false);
      }
    };
    
    fetchODStats();
  }, [currentUser, selectedEvent, navigate]);

  const eligibleForIQAC = useMemo(() => {
    if (!selectedEvent) return false;
    const isApprovedStatus = selectedEvent.status === EventStatus.COMPLETED || selectedEvent.status === EventStatus.POSTED;
    const isEventEnded = isEventEndTimePassed(selectedEvent);
    return isApprovedStatus && isEventEnded;
  }, [selectedEvent]);

  const eventInfo = useMemo(() => {
    if (!selectedEvent) return null;
    const step1 = selectedEvent.requisition?.step1;

    return {
      title: selectedEvent.title || step1?.eventName || '-',
      organizerName: selectedEvent.organizerName || step1?.organizerDetails?.organizerName || '-',
      department: step1?.organizerDetails?.department || selectedEvent.department || 'Computer Science and Engineering',
      eventType: selectedEvent.eventType || step1?.eventType || '-',
      eventDate: toDateRange(selectedEvent),
      venue: selectedEvent.venue || selectedEvent.requisition?.annexureII_audio?.venueName || '-',
      professionalSociety: Array.isArray(step1?.professionalSocieties) && step1.professionalSocieties.length
        ? step1.professionalSocieties.join(', ')
        : '-',
      iicEvent: yesNo(step1?.isIIC),
    };
  }, [selectedEvent]);

  const getStatus = (item) => {
    if (verified[item.id]) return 'verified';
    if (item.autoGenerated) return 'autoGenerated';
    if (uploads[item.id]) return 'uploaded';
    return 'pending';
  };

  const completedCount = useMemo(
    () => CHECKLIST_ITEMS.filter((item) => getStatus(item) !== 'pending').length,
    [uploads, verified]
  );

  const progressPercent = Math.round((completedCount / CHECKLIST_ITEMS.length) * 100);

  const hasStudentRoster = studentAttendanceRoster.length > 0;
  const studentsRegisteredFromRoster = studentAttendanceRoster.length;
  const studentsAttendedFromRoster = studentAttendanceRoster.filter((item) => item.attendanceStatus === 'ATTENDED').length;
  const studentsNoShowFromRoster = Math.max(studentsRegisteredFromRoster - studentsAttendedFromRoster, 0);
  const studentAttendancePercent = studentsRegisteredFromRoster > 0
    ? `${Math.round((studentsAttendedFromRoster / studentsRegisteredFromRoster) * 100)}%`
    : '0%';

  useEffect(() => {
    if (!hasStudentRoster) return;

    setRegistrationDetails((prev) => {
      const nextStudentsCount = studentsRegisteredFromRoster;
      const nextStudentsAttended = studentsAttendedFromRoster;

      if (
        Number(prev.studentsCount) === nextStudentsCount &&
        Number(prev.studentsAttended) === nextStudentsAttended
      ) {
        return prev;
      }

      return {
        ...prev,
        studentsCount: nextStudentsCount,
        studentsAttended: nextStudentsAttended,
      };
    });
  }, [hasStudentRoster, studentsRegisteredFromRoster, studentsAttendedFromRoster]);

  const totalRegistered =
    (Number(registrationDetails.studentsCount) || 0) +
    (Number(registrationDetails.facultyCount) || 0) +
    (Number(registrationDetails.externalCount) || 0);

  const totalAttended =
    (Number(registrationDetails.studentsAttended) || 0) +
    (Number(registrationDetails.facultyAttended) || 0) +
    (Number(registrationDetails.externalAttended) || 0);

  const noShowCount = Math.max(totalRegistered - totalAttended, 0);

  const onUpload = (itemId, e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // ── Size guard: reject immediately if > 250 KB ──
    if (file.size > MAX_DOC_SIZE) {
      setUploadErrors((prev) => ({
        ...prev,
        [itemId]: `File too large (${(file.size / 1024).toFixed(0)} KB). Maximum allowed is ${MAX_DOC_SIZE_LABEL}.`,
      }));
      e.target.value = '';
      return;
    }

    // Clear any previous error for this item
    setUploadErrors((prev) => { const next = { ...prev }; delete next[itemId]; return next; });

    const reader = new FileReader();
    reader.onload = (event) => {
      setUploads((prev) => ({
        ...prev,
        [itemId]: {
          fileName: file.name,
          fileType: file.type,
          fileSize: file.size,
          dataUrl: event.target?.result || '',
          uploadedAt: new Date().toISOString(),
        },
      }));
      setSubmitError('');
      setValidationError('');
      e.target.value = '';
    };
    reader.onerror = () => {
      setSubmitError('Unable to read uploaded file. Please try again.');
      e.target.value = '';
    };
    reader.readAsDataURL(file);
  };

  const toggleVerified = (item) => {
    const currentStatus = getStatus(item);
    if (currentStatus === 'pending') return;

    setVerified((prev) => ({
      ...prev,
      [item.id]: !prev[item.id],
    }));
  };

  const onGalleryUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setGallery((prev) => [...prev, {
        id: Date.now(),
        fileName: file.name,
        dataUrl: event.target.result,
        title: '',
        caption: '',
      }]);
    };
    reader.readAsDataURL(file);
    e.target.value = '';
  };

  const removeGalleryItem = (id) => {
    setGallery((prev) => prev.filter((item) => item.id !== id));
  };

  const addResourcePerson = () => {
    if (!resourcePersonForm.name.trim()) {
      alert('Please fill in the Resource Person Name');
      return;
    }
    setResourcePersons((prev) => [...prev, {
      id: Date.now(),
      ...resourcePersonForm,
    }]);
    setResourcePersonForm({
      name: '',
      designation: '',
      organization: '',
      topic: '',
      rating: 5,
    });
  };

  const removeResourcePerson = (id) => {
    setResourcePersons((prev) => prev.filter((item) => item.id !== id));
  };

  const addGuestFeedback = () => {
    if (!feedbackForm.name.trim() || !feedbackForm.feedback.trim()) {
      alert('Please fill in Name and Feedback');
      return;
    }
    setGuestFeedback((prev) => [...prev, {
      id: Date.now(),
      ...feedbackForm,
    }]);
    setFeedbackForm({
      name: '',
      designation: '',
      organization: '',
      rating: 5,
      feedback: '',
    });
  };

  const removeGuestFeedback = (id) => {
    setGuestFeedback((prev) => prev.filter((item) => item.id !== id));
  };

  const updateStudentAttendanceStatus = (rowId, attendanceStatus) => {
    setStudentAttendanceRoster((prev) => prev.map((row) => (
      row.id === rowId
        ? { ...row, attendanceStatus: attendanceStatus === 'NOT_ATTENDED' ? 'NOT_ATTENDED' : 'ATTENDED' }
        : row
    )));
  };

  const handleSubmit = async () => {
    const missing = CHECKLIST_ITEMS.filter((item) => !item.autoGenerated && !uploads[item.id]);
    if (missing.length > 0) {
      setValidationError(`Please upload all required documents before submission. Missing: ${missing.length}.`);
      return;
    }

    // Guard: ensure no uploaded file exceeds the size limit
    const oversized = CHECKLIST_ITEMS.filter(
      (item) => !item.autoGenerated && uploads[item.id] && uploads[item.id].fileSize > MAX_DOC_SIZE
    );
    if (oversized.length > 0) {
      setValidationError(
        `${oversized.length} document(s) exceed the ${MAX_DOC_SIZE_LABEL} limit: ${oversized.map((i) => i.label).join(', ')}. Please re-upload smaller files.`
      );
      return;
    }

    const studentsCount = hasStudentRoster
      ? studentsRegisteredFromRoster
      : (Number(registrationDetails.studentsCount) || 0);
    const facultyCount = Number(registrationDetails.facultyCount) || 0;
    const externalCount = Number(registrationDetails.externalCount) || 0;
    const studentsAttended = hasStudentRoster
      ? studentsAttendedFromRoster
      : (Number(registrationDetails.studentsAttended) || 0);
    const facultyAttended = Number(registrationDetails.facultyAttended) || 0;
    const externalAttended = Number(registrationDetails.externalAttended) || 0;

    if (
      studentsAttended > studentsCount ||
      facultyAttended > facultyCount ||
      externalAttended > externalCount
    ) {
      setValidationError('Actual attendance cannot exceed registered count in any category.');
      return;
    }

    setValidationError('');
    setSubmitError('');
    setIsSubmitting(true);

    try {
      const checklist = CHECKLIST_ITEMS.map((item) => ({
        id: item.id,
        requirement: item.label,
        status: getStatus(item),
        autoGenerated: Boolean(item.autoGenerated),
        file: uploads[item.id] || null,
      }));

      const documents = Object.fromEntries(
        CHECKLIST_ITEMS.map((item) => {
          if (item.autoGenerated) {
            return [item.label, {
              autoGenerated: true,
              status: getStatus(item),
              source: item.id === 'attendance-sheet'
                ? 'Registration system'
                : item.id === 'feedback-participants'
                  ? 'Feedback module'
                  : 'Post Event Report module',
            }];
          }

          return [item.label, {
            ...(uploads[item.id] || {}),
            status: getStatus(item),
            verified: Boolean(verified[item.id]),
          }];
        })
      );

      const payload = {
        eventOutcome: 'IQAC documentation checklist submitted.',
        registrationDetails: {
          studentsCount,
          facultyCount,
          externalCount,
          studentsAttended,
          facultyAttended,
          externalAttended,
          studentAttendanceList: studentAttendanceRoster.map((row) => ({
            id: row.id,
            requestId: row.requestId || '',
            student: row.student || '',
            rollNo: row.rollNo || '',
            attendanceStatus: row.attendanceStatus,
          })),
          periodStart: registrationDetails.periodStart,
          periodEnd: registrationDetails.periodEnd,
          mode: registrationDetails.mode,
        },
        resourcePersons: resourcePersons.map(({ id, ...item }) => item),
        gallery: gallery.map(({ id, ...item }) => item),
        guestFeedbackList: guestFeedback.map(({ id, ...item }) => item),
        documents,
        finalReport: documents['Event Report'] || null,
        checklist,
        iqacSubmissionCompletedAt: new Date().toISOString(),
      };

      const response = await fetch(`http://localhost:5001/api/iqac/${selectedEvent.id}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      if (!response.ok || !data.success) {
        throw new Error(data.message || 'Failed to submit IQAC documentation.');
      }

      navigate('/dashboard');
    } catch (error) {
      setSubmitError(error.message || 'Unable to submit IQAC documentation.');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!currentUser || !selectedEvent || !eventInfo) return null;

  return (
    <div className="min-h-screen bg-slate-50 pb-14">
      <Navbar />

      <main className="max-w-6xl mx-auto px-6 py-8 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <button onClick={() => navigate('/dashboard')} className="btn-secondary whitespace-nowrap md:order-2">
            Back to Dashboard
          </button>
        </div>

        <header className="rounded-2xl border border-slate-200 bg-gradient-to-br from-white via-slate-50 to-blue-50/50 p-6 shadow-sm">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div>
              <h1 className="text-2xl font-bold text-slate-900">IQAC Submission Checklist</h1>
              <p className="mt-2 max-w-2xl text-sm text-slate-600">
                Final step of the event lifecycle. Upload, verify, and lock all documentation for a complete IQAC closure report.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm lg:min-w-[320px]">
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Completed</p>
                <p className="mt-1 font-bold text-slate-900">{completedCount}/{CHECKLIST_ITEMS.length}</p>
              </div>
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Progress</p>
                <p className="mt-1 font-bold text-cse-accent">{progressPercent}%</p>
              </div>
              <div className="col-span-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Event</p>
                <p className="mt-1 truncate font-semibold text-slate-900">{eventInfo.title}</p>
              </div>
            </div>
          </div>

          <div className="mt-5">
            <div className="mb-2 flex items-center justify-between text-sm font-semibold text-slate-700">
              <span>IQAC Documentation Progress</span>
              <span>{completedCount} / {CHECKLIST_ITEMS.length} Documents Completed</span>
            </div>
            <div className="h-3 w-full overflow-hidden rounded-full bg-slate-100">
              <div
                className="h-full rounded-full bg-cse-accent transition-all"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>
        </header>

        {!eligibleForIQAC && (
          <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5">
            <div className="flex items-start gap-3">
              <AlertCircle className="mt-0.5 text-amber-600" size={18} />
              <div>
                <p className="text-sm font-bold text-amber-800">IQAC checklist is not available</p>
                <p className="mt-1 text-sm text-amber-700">
                  IQAC submission is only available after the event has ended and must be completed within 7 days of the event end time.
                </p>
              </div>
            </div>
          </section>
        )}

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 1 - Event Information (Read-only)</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
            {[
              ['Event Title', eventInfo.title],
              ['Event Organizer Name', eventInfo.organizerName],
              ['Department', eventInfo.department],
              ['Event Type', eventInfo.eventType],
              ['Event Date (From - To)', eventInfo.eventDate],
              ['Event Venue', eventInfo.venue],
              ['Professional Society', eventInfo.professionalSociety],
              ['IIC Event', eventInfo.iicEvent],
            ].map(([label, value]) => (
              <div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
                <p className="mt-1 text-sm font-medium text-slate-900">{value || '-'}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 2 - Registration Details</h2>
          <p className="mt-1 text-sm text-slate-600">Capture both registration and actual attendance to account for no-shows</p>

          {autoAttendanceStats && (
            <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">
              {[
                ['Registered', autoAttendanceStats.totalRegistered],
                ['Approved', autoAttendanceStats.approved],
                ['Rejected', autoAttendanceStats.rejected],
                ['Approval Rate (OD)', autoAttendanceStats.attendanceRate],
              ].map(([label, value]) => (
                <div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
                  <p className="mt-1 text-sm font-bold text-slate-900">{value ?? '-'}</p>
                </div>
              ))}
            </div>
          )}

          <p className="mt-3 text-xs text-slate-500">
            Note: OD stats above are registration workflow data. Enter actual attendees below for final IQAC reporting.
          </p>

          <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
            <div>
              <label className="block text-sm font-semibold text-slate-700">Students Registered</label>
              <input
                type="number"
                value={registrationDetails.studentsCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, studentsCount: e.target.value }))}
                disabled={isSubmitting || hasStudentRoster}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Faculty Registered</label>
              <input
                type="number"
                value={registrationDetails.facultyCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, facultyCount: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">External Registered</label>
              <input
                type="number"
                value={registrationDetails.externalCount}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, externalCount: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Students Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.studentsAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, studentsAttended: e.target.value }))}
                disabled={isSubmitting || hasStudentRoster}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Faculty Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.facultyAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, facultyAttended: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">External Attended (Actual)</label>
              <input
                type="number"
                value={registrationDetails.externalAttended}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, externalAttended: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">Registration Mode</label>
              <select
                value={registrationDetails.mode}
                onChange={(e) => setRegistrationDetails((prev) => ({ ...prev, mode: e.target.value }))}
                disabled={isSubmitting}
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
              >
                <option>In-person</option>
                <option>Online</option>
                <option>Hybrid</option>
              </select>
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Registered</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{totalRegistered}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Attended</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{totalAttended}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">No-Show Count</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{noShowCount}</p>
            </div>
          </div>

          {hasStudentRoster && (
            <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <h3 className="text-sm font-bold text-slate-900">Student Attendance Marking</h3>
                <p className="text-xs text-slate-600">
                  Attended: <span className="font-semibold text-emerald-700">{studentsAttendedFromRoster}</span> / {studentsRegisteredFromRoster}
                  {' '}| No-show: <span className="font-semibold text-amber-700">{studentsNoShowFromRoster}</span>
                  {' '}| Attendance: <span className="font-semibold text-cse-accent">{studentAttendancePercent}</span>
                </p>
              </div>

              <div className="mt-3 max-h-72 overflow-y-auto rounded-lg border border-slate-200 bg-white">
                <table className="min-w-full text-sm">
                  <thead className="sticky top-0 bg-slate-100">
                    <tr>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">#</th>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">Student</th>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">Roll No</th>
                      <th className="px-3 py-2 text-left font-semibold text-slate-700">Attendance</th>
                    </tr>
                  </thead>
                  <tbody>
                    {studentAttendanceRoster.map((row, idx) => (
                      <tr key={row.id || `${row.rollNo}-${idx + 1}`} className="border-t border-slate-100">
                        <td className="px-3 py-2 text-slate-700">{idx + 1}</td>
                        <td className="px-3 py-2 text-slate-800">{row.student || '-'}</td>
                        <td className="px-3 py-2 text-slate-600">{row.rollNo || '-'}</td>
                        <td className="px-3 py-2">
                          <select
                            value={row.attendanceStatus}
                            onChange={(e) => updateStudentAttendanceStatus(row.id, e.target.value)}
                            disabled={isSubmitting}
                            className="w-full rounded-lg border border-slate-300 px-2 py-1.5 text-xs font-semibold text-slate-700"
                          >
                            <option value="ATTENDED">Attended</option>
                            <option value="NOT_ATTENDED">Not Attended</option>
                          </select>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 3 - Student Feedback (Auto from registrations)</h2>
          <p className="mt-1 text-sm text-slate-600">Collected automatically from approved students who submitted post-event feedback</p>

          <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3">
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Responses</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{autoFeedbackSummary?.totalResponses ?? 0}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Average Rating</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{autoFeedbackSummary?.averageRating ?? '-'}</p>
            </div>
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Scale</p>
              <p className="mt-1 text-sm font-bold text-slate-900">{autoFeedbackSummary?.ratingOutOf || 5}</p>
            </div>
          </div>

          {autoFeedbackSummary?.comments?.length > 0 ? (
            <div className="mt-4 space-y-2 max-h-64 overflow-y-auto pr-1">
              {autoFeedbackSummary.comments.map((item, idx) => (
                <div key={`${item.student}-${idx}`} className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                  <p className="text-sm font-semibold text-slate-900">{item.student} <span className="text-xs text-slate-500">({item.rollNo})</span></p>
                  <p className="text-xs text-amber-600 mt-0.5">Rating: {item.rating}/5</p>
                  {item.comment ? <p className="text-sm text-slate-700 mt-1">{item.comment}</p> : <p className="text-xs text-slate-500 mt-1">No comment</p>}
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-4 text-sm text-slate-500">No student feedback submitted yet.</p>
          )}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 4 - Event Gallery</h2>
          <p className="mt-1 text-sm text-slate-600">Upload photos and images from the event</p>
          
          <div className="mt-4 space-y-4">
            <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-cse-accent/30 bg-cse-accent/5 px-4 py-2.5 text-sm font-semibold text-cse-accent hover:bg-cse-accent/10 disabled:opacity-60">
              <Upload size={16} /> Add Photo
              <input
                type="file"
                accept=".jpg,.jpeg,.png,.gif"
                className="hidden"
                onChange={onGalleryUpload}
                disabled={isSubmitting}
              />
            </label>

            {gallery.length > 0 && (
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                {gallery.map((item) => (
                  <div key={item.id} className="rounded-lg border border-slate-200 p-3">
                    <img
                      src={item.dataUrl}
                      alt="gallery"
                      className="w-full h-32 object-cover rounded-lg mb-2"
                    />
                    <div className="space-y-2">
                      <input
                        type="text"
                        placeholder="Photo title (optional)"
                        value={item.title}
                        onChange={(e) => setGallery((prev) =>
                          prev.map((g) => g.id === item.id ? { ...g, title: e.target.value } : g)
                        )}
                        className="w-full text-xs rounded border border-slate-300 px-2 py-1"
                      />
                      <button
                        type="button"
                        onClick={() => removeGalleryItem(item.id)}
                        className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                      >
                        <X size={14} /> Remove
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {gallery.length === 0 && (
              <p className="text-sm text-slate-500">No photos uploaded yet.</p>
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 5 - Guest Feedback</h2>
          <p className="mt-1 text-sm text-slate-600">Collect feedback from resource persons and guests</p>
          
          <div className="mt-4 space-y-4">
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-3">
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Name *</label>
                  <input
                    type="text"
                    placeholder="Full name"
                    value={feedbackForm.name}
                    onChange={(e) => setFeedbackForm((prev) => ({ ...prev, name: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Designation</label>
                  <input
                    type="text"
                    placeholder="e.g., Professor, Industry Expert"
                    value={feedbackForm.designation}
                    onChange={(e) => setFeedbackForm((prev) => ({ ...prev, designation: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
              </div>
              
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Organization</label>
                  <input
                    type="text"
                    placeholder="Organization name"
                    value={feedbackForm.organization}
                    onChange={(e) => setFeedbackForm((prev) => ({ ...prev, organization: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Rating (1-5) *</label>
                  <div className="mt-1 flex items-center gap-2">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        key={star}
                        type="button"
                        onClick={() => setFeedbackForm((prev) => ({ ...prev, rating: star }))}
                        disabled={isSubmitting}
                        className={`text-2xl transition ${feedbackForm.rating >= star ? 'text-yellow-400' : 'text-slate-300'}`}
                      >
                        <Star size={20} fill="currentColor" />
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div>
                <label className="text-sm font-semibold text-slate-700">Feedback *</label>
                <textarea
                  placeholder="Guest feedback and comments"
                  value={feedbackForm.feedback}
                  onChange={(e) => setFeedbackForm((prev) => ({ ...prev, feedback: e.target.value }))}
                  disabled={isSubmitting}
                  rows={3}
                  className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                />
              </div>

              <button
                type="button"
                onClick={addGuestFeedback}
                disabled={isSubmitting}
                className="inline-flex items-center gap-2 rounded-lg bg-cse-accent px-4 py-2 text-sm font-semibold text-white hover:bg-cse-accent/90 disabled:opacity-60"
              >
                <Plus size={16} /> Add Feedback
              </button>
            </div>

            {guestFeedback.length > 0 && (
              <div className="space-y-2">
                <p className="text-sm font-semibold text-slate-700">Added Feedback ({guestFeedback.length})</p>
                {guestFeedback.map((feedback) => (
                  <div key={feedback.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3 space-y-2">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-semibold text-slate-900">{feedback.name}</p>
                        {feedback.designation && <p className="text-xs text-slate-600">{feedback.designation}</p>}
                        {feedback.organization && <p className="text-xs text-slate-600">{feedback.organization}</p>}
                      </div>
                      <button
                        type="button"
                        onClick={() => removeGuestFeedback(feedback.id)}
                        className="text-red-600 hover:text-red-700"
                      >
                        <X size={18} />
                      </button>
                    </div>
                    <div className="flex items-center gap-1">
                      {[1, 2, 3, 4, 5].map((star) => (
                        <Star
                          key={star}
                          size={14}
                          fill={feedback.rating >= star ? 'currentColor' : 'none'}
                          className={feedback.rating >= star ? 'text-yellow-400' : 'text-slate-300'}
                        />
                      ))}
                      <span className="text-xs text-slate-600 ml-2">({feedback.rating}/5)</span>
                    </div>
                    <p className="text-sm text-slate-700">{feedback.feedback}</p>
                  </div>
                ))}
              </div>
            )}
            {guestFeedback.length === 0 && (
              <p className="text-sm text-slate-500">No guest feedback added yet.</p>
            )}
          </div>
        </section>

        {/* ── Section 6 – Resource Persons ── */}
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">Section 6 - Resource Persons / Speakers</h2>
          <p className="mt-1 text-sm text-slate-600">Add details of all resource persons and speakers who participated in the event</p>

          <div className="mt-4 space-y-4">
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-3">
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Name *</label>
                  <input
                    type="text"
                    placeholder="Full name"
                    value={resourcePersonForm.name}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, name: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Designation</label>
                  <input
                    type="text"
                    placeholder="e.g., Professor, Industry Expert"
                    value={resourcePersonForm.designation}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, designation: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <label className="text-sm font-semibold text-slate-700">Organization / Institution</label>
                  <input
                    type="text"
                    placeholder="Organization name"
                    value={resourcePersonForm.organization}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, organization: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-700">Topic / Session</label>
                  <input
                    type="text"
                    placeholder="Topic presented"
                    value={resourcePersonForm.topic}
                    onChange={(e) => setResourcePersonForm((prev) => ({ ...prev, topic: e.target.value }))}
                    disabled={isSubmitting}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"
                  />
                </div>
              </div>

              <div>
                <label className="text-sm font-semibold text-slate-700">Session Rating (1–5)</label>
                <div className="mt-1 flex items-center gap-2">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <button
                      key={star}
                      type="button"
                      onClick={() => setResourcePersonForm((prev) => ({ ...prev, rating: star }))}
                      disabled={isSubmitting}
                      className={`text-2xl transition ${resourcePersonForm.rating >= star ? 'text-yellow-400' : 'text-slate-300'}`}
                    >
                      <Star size={20} fill="currentColor" />
                    </button>
                  ))}
                </div>
              </div>

              <button
                type="button"
                onClick={addResourcePerson}
                disabled={isSubmitting}
                className="inline-flex items-center gap-2 rounded-lg bg-cse-accent px-4 py-2 text-sm font-semibold text-white hover:bg-cse-accent/90 disabled:opacity-60"
              >
                <Plus size={16} /> Add Resource Person
              </button>
            </div>

            {resourcePersons.length > 0 && (
              <div className="space-y-2">
                <p className="text-sm font-semibold text-slate-700">Added Resource Persons ({resourcePersons.length})</p>
                {resourcePersons.map((person) => (
                  <div key={person.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3 space-y-1">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-semibold text-slate-900">{person.name}</p>
                        {person.designation && <p className="text-xs text-slate-600">{person.designation}</p>}
                        {person.organization && <p className="text-xs text-slate-600">{person.organization}</p>}
                        {person.topic && <p className="text-xs text-slate-500 mt-0.5">Topic: {person.topic}</p>}
                      </div>
                      <button
                        type="button"
                        onClick={() => removeResourcePerson(person.id)}
                        className="text-red-600 hover:text-red-700"
                      >
                        <X size={18} />
                      </button>
                    </div>
                    <div className="flex items-center gap-1">
                      {[1, 2, 3, 4, 5].map((star) => (
                        <Star
                          key={star}
                          size={14}
                          fill={person.rating >= star ? 'currentColor' : 'none'}
                          className={person.rating >= star ? 'text-yellow-400' : 'text-slate-300'}
                        />
                      ))}
                      <span className="text-xs text-slate-600 ml-2">({person.rating}/5)</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {resourcePersons.length === 0 && (
              <p className="text-sm text-slate-500">No resource persons added yet.</p>
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h2 className="text-lg font-bold text-slate-900">Section 7 - IQAC Documentation Checklist</h2>
            <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600">
              {CHECKLIST_ITEMS.length} Required Items
            </span>
          </div>

          {/* ── 250 KB upfront notice ── */}
          <div className="mt-3 flex items-start gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3">
            <AlertCircle size={15} className="mt-0.5 shrink-0 text-blue-600" />
            <p className="text-xs text-blue-800">
              <span className="font-bold">Document size limit: {MAX_DOC_SIZE_LABEL} per file.</span>{' '}
              Please compress or reduce your documents before uploading. Files exceeding {MAX_DOC_SIZE_LABEL} will be rejected automatically.
              Accepted formats: PDF, DOC, DOCX, JPG, PNG.
            </p>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 lg:grid-cols-2">
            {CHECKLIST_ITEMS.map((item, index) => {
              const status = getStatus(item);
              const file = uploads[item.id];
              const canVerify = status === 'uploaded' || status === 'autoGenerated' || status === 'verified';

              return (
                <article
                  key={item.id}
                  className={`rounded-xl border p-4 ${
                    uploadErrors[item.id]
                      ? 'border-red-300 bg-red-50/60'
                      : 'border-slate-200 bg-slate-50/50'
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Requirement {index + 1}</p>
                      <h3 className="mt-1 text-sm font-semibold text-slate-900">{item.label}</h3>
                    </div>
                    <StatusBadge status={status} />
                  </div>

                  <div className="mt-3 space-y-2">
                    {item.autoGenerated ? (
                      <span className="inline-flex items-center rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700">
                        Auto from system
                      </span>
                    ) : (
                      <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-cse-accent/30 bg-cse-accent/5 px-3 py-1.5 text-xs font-semibold text-cse-accent hover:bg-cse-accent/10">
                        <Upload size={14} /> Upload Document
                        <input
                          type="file"
                          accept={ACCEPTED_TYPES}
                          className="hidden"
                          onChange={(e) => onUpload(item.id, e)}
                          disabled={!eligibleForIQAC || isSubmitting}
                        />
                      </label>
                    )}

                    {/* Per-item upload error (size exceeded) */}
                    {uploadErrors[item.id] && (
                      <p className="flex items-center gap-1.5 text-xs font-semibold text-red-600">
                        <AlertCircle size={13} />
                        {uploadErrors[item.id]}
                      </p>
                    )}

                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-xs text-slate-500">
                        {file
                          ? `File: ${file.fileName}`
                          : item.autoGenerated
                          ? 'Generated from workflow data'
                          : `Max ${MAX_DOC_SIZE_LABEL} · PDF, DOC, DOCX, JPG, PNG`}
                      </p>
                      {/* File size pill */}
                      {file && (
                        <span
                          className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold ${
                            file.fileSize > MAX_DOC_SIZE
                              ? 'bg-red-100 text-red-700'
                              : 'bg-emerald-100 text-emerald-700'
                          }`}
                        >
                          {(file.fileSize / 1024).toFixed(1)} KB
                        </span>
                      )}
                      {file && file.dataUrl && (
                        <a
                          href={file.dataUrl}
                          download={file.fileName}
                          className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 hover:bg-blue-100"
                        >
                          Download
                        </a>
                      )}
                    </div>

                    {canVerify && (
                      <button
                        type="button"
                        onClick={() => toggleVerified(item)}
                        disabled={!eligibleForIQAC || isSubmitting}
                        className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 disabled:opacity-60"
                      >
                        <CheckCircle2 size={12} />
                        {status === 'verified' ? 'Unverify' : 'Mark Verified'}
                      </button>
                    )}
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        {(validationError || submitError) && (
          <section className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {validationError || submitError}
          </section>
        )}

        <footer className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs text-slate-500">
            Final submission validates all required documents and closes the event as IQAC Submission Completed.
          </p>
          <button
            type="button"
            onClick={handleSubmit}
            disabled={isSubmitting || !eligibleForIQAC || Boolean(selectedEvent.iqacSubmittedAt)}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-cse-accent px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400"
          >
            {isSubmitting ? <Loader2 size={16} className="animate-spin" /> : <FileCheck2 size={16} />}
            {selectedEvent.iqacSubmittedAt ? 'IQAC Already Submitted' : 'Submit IQAC Documentation'}
          </button>
        </footer>
      </main>
    </div>
  );
};

export default IQACSubmission;
