export const UserRole = {
  FACULTY: 'FACULTY',
  HOD: 'HOD',
  HR_TEAM: 'HR_TEAM',
  AUDIO_TEAM: 'AUDIO_TEAM',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  TRANSPORT_TEAM: 'TRANSPORT_TEAM',
  BOYS_WARDEN: 'BOYS_WARDEN',
  GIRLS_WARDEN: 'GIRLS_WARDEN',
  MEDIA: 'MEDIA',
  STUDENT_ORGANIZER: 'STUDENT_ORGANIZER',
  STUDENT_GENERAL: 'STUDENT_GENERAL',
};

export const EventStatus = {
  PENDING_FACULTY: 'PENDING_FACULTY',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_DEPARTMENTS: 'PENDING_DEPARTMENTS',
  PENDING_IQAC: 'PENDING_IQAC',
  APPROVED: 'APPROVED',
  POSTED: 'POSTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

export const ODRequestStatus = {
  PENDING_ORGANIZER: 'PENDING_ORGANIZER',
  PENDING_FACULTY: 'PENDING_FACULTY',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_PRINCIPAL: 'PENDING_PRINCIPAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};
