export const UserRole = {
  FACULTY: 'FACULTY',
  HOD: 'HOD',
  PRINCIPAL: 'PRINCIPAL',
  MEDIA: 'MEDIA',
  STUDENT_ORGANIZER: 'STUDENT_ORGANIZER',
  STUDENT_GENERAL: 'STUDENT_GENERAL',
};

export const EventStatus = {
  PENDING_FACULTY: 'PENDING_FACULTY',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_PRINCIPAL: 'PENDING_PRINCIPAL',
  APPROVED: 'APPROVED',
  POSTED: 'POSTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

export const ODRequestStatus = {
  PENDING_ORGANIZER: 'PENDING_ORGANIZER',
  PENDING_FACULTY: 'PENDING_FACULTY',
  PENDING_HOD: 'PENDING_HOD',
  PENDING_PRINCIPAL: 'PENDING_PRINCIPAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};
